In [1]:
import pandas as pd

aluminum = pd.read_csv("WHITESANDLAKE_Aluminum.csv", encoding="latin1")
calcium = pd.read_csv("WHITESANDLAKE_Calcium.csv", encoding="latin1")
copper = pd.read_csv("WHITESANDLAKE_Copper.csv", encoding="latin1")
lead = pd.read_csv("WHITESANDLAKE_Lead.csv", encoding="latin1")
nickle = pd.read_csv("WHITESANDLAKE_Nickle.csv", encoding="latin1")
phosphorus = pd.read_csv("WHITESANDLAKE_Phosphorus.csv", encoding="latin1")
vanadium = pd.read_csv("WHITESANDLAKE_Vanadium.csv", encoding="latin1")

In [2]:

 #convert timestamp
aluminum["Sampling Timestamp"] = pd.to_datetime(aluminum["Sampling Timestamp"], errors="coerce")

# drop unnecessary columns
aluminum = aluminum.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])

# clean units
#aluminum["Unit Symbol"] = aluminum["Unit Symbol"].str.replace("u","µ")"""
aluminum.head(5)

C:\Users\morsal.n\AppData\Local\Temp\ipykernel_34616\4052404462.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  aluminum["Sampling Timestamp"] = pd.to_datetime(aluminum["Sampling Timestamp"], errors="coerce")

,Sampling Timestamp,Aluminum Dissolved,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2003-08-29 13:45:00,78.3,WHITESAND LAKE,'---,µg/l,2837,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,DISCRETE SAMPLE (GRAB)
1,2004-08-29 15:10:00,64.5,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
2,2007-08-27 12:30:00,62.7,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,DISCRETE SAMPLE (GRAB)
3,2008-09-02 14:00:00,98.3,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,DISCRETE SAMPLE (GRAB)
4,2009-08-16 12:30:00,128.0,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,DISCRETE SAMPLE (GRAB)

In [3]:

calcium["Sampling Timestamp"] = pd.to_datetime(
    calcium["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
calcium = calcium.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])

calcium["Calcium Dissolved"] = calcium["Calcium Dissolved"] * 1000

calcium["Unit Symbol"] = calcium["Unit Symbol"].str.replace("m","µ")

calcium.head(5)

,Sampling Timestamp,Calcium Dissolved,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2000-09-06 12:40:00,6590.0,WHITESAND LAKE,'---,µg/l,482,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.003,Centre,EUPHOTIC COMPOSITE
1,2001-10-04 13:06:00,6210.0,WHITESAND LAKE,'---,µg/l,482,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.003,Centre,VERTICAL INTEGRATED
2,2002-10-09 14:00:00,5230.0,WHITESAND LAKE,'---,µg/l,482,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.003,Centre,DISCRETE SAMPLE (GRAB)
3,2003-08-29 13:45:00,5350.0,WHITESAND LAKE,'---,µg/l,482,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.003,Centre,DISCRETE SAMPLE (GRAB)
4,2004-08-29 15:10:00,4870.0,WHITESAND LAKE,'---,µg/l,482,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.003,Centre,SINGLE EUPHOTIC COMPOSITE

In [4]:
copper["Sampling Timestamp"] = pd.to_datetime(
    copper["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
copper = copper.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
copper.head(10)

C:\Users\morsal.n\AppData\Local\Temp\ipykernel_34616\2586682039.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  copper["Sampling Timestamp"] = pd.to_datetime(

,Sampling Timestamp,Copper Dissolved,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2003-08-29 13:45:00,1.200,WHITESAND LAKE,'---,µg/l,2837,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,DISCRETE SAMPLE (GRAB)
1,2004-08-29 15:10:00,0.893,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
2,2007-08-27 12:30:00,0.446,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,DISCRETE SAMPLE (GRAB)
3,2008-09-02 14:00:00,0.927,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,DISCRETE SAMPLE (GRAB)
4,2009-08-16 12:30:00,0.844,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,DISCRETE SAMPLE (GRAB)
5,2010-08-30 12:30:00,0.725,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.10,Centre,DISCRETE SAMPLE (GRAB)
6,2011-08-31 11:30:00,1.400,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.10,Centre,DISCRETE SAMPLE (GRAB)
7,2012-08-27 13:15:00,0.785,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.10,Centre,SINGLE EUPHOTIC COMPOSITE
8,2013-09-05 12:20:00,0.838,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.10,Centre,DISCRETE SAMPLE (GRAB)
9,2015-08-25 13:00:00,0.660,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.08,Centre,SINGLE EUPHOTIC COMPOSITE

In [5]:
lead["Sampling Timestamp"] = pd.to_datetime(
    lead["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
lead = lead.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
lead.head(10)

C:\Users\morsal.n\AppData\Local\Temp\ipykernel_34616\2676204525.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  lead["Sampling Timestamp"] = pd.to_datetime(

,Sampling Timestamp,Lead Dissolved,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2003-08-29 13:45:00,0.1890,WHITESAND LAKE,'---,µg/l,2837,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,DISCRETE SAMPLE (GRAB)
1,2004-08-29 15:10:00,0.1010,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
2,2007-08-27 12:30:00,0.0545,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,DISCRETE SAMPLE (GRAB)
3,2008-09-02 14:00:00,0.1720,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,DISCRETE SAMPLE (GRAB)
4,2009-08-16 12:30:00,0.1780,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,DISCRETE SAMPLE (GRAB)
5,2010-08-30 12:30:00,0.1510,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.100,Centre,DISCRETE SAMPLE (GRAB)
6,2011-08-31 11:30:00,0.2990,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.100,Centre,DISCRETE SAMPLE (GRAB)
7,2012-08-27 13:15:00,0.0800,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.100,Centre,SINGLE EUPHOTIC COMPOSITE
8,2013-09-05 12:20:00,0.1280,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.100,Centre,DISCRETE SAMPLE (GRAB)
9,2015-08-25 13:00:00,0.1170,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.004,Centre,SINGLE EUPHOTIC COMPOSITE

In [6]:
nickle["Sampling Timestamp"] = pd.to_datetime(
    nickle["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
nickle = nickle.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
nickle.head(10)

C:\Users\morsal.n\AppData\Local\Temp\ipykernel_34616\1055445505.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  nickle["Sampling Timestamp"] = pd.to_datetime(

,Sampling Timestamp,Nickel Dissolved,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2003-08-29 13:45:00,0.770,WHITESAND LAKE,'---,µg/l,2840,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,DISCRETE SAMPLE (GRAB)
1,2004-08-29 15:10:00,0.977,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
2,2007-08-27 12:30:00,0.833,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,DISCRETE SAMPLE (GRAB)
3,2008-09-02 14:00:00,0.914,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,DISCRETE SAMPLE (GRAB)
4,2009-08-16 12:30:00,0.995,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,DISCRETE SAMPLE (GRAB)
5,2010-08-30 12:30:00,0.951,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.100,Centre,DISCRETE SAMPLE (GRAB)
6,2011-08-31 11:30:00,0.912,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.100,Centre,DISCRETE SAMPLE (GRAB)
7,2012-08-27 13:15:00,0.865,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.100,Centre,SINGLE EUPHOTIC COMPOSITE
8,2013-09-05 12:20:00,1.180,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.100,Centre,DISCRETE SAMPLE (GRAB)
9,2015-08-25 13:00:00,0.841,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.006,Centre,SINGLE EUPHOTIC COMPOSITE

In [7]:
"""nitrogen["Sampling Timestamp"] = pd.to_datetime(
    nitrogen["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
nitrogen = nitrogen.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
nitrogen ["Nitrogen Dissolved"] = nitrogen["Nitrogen Dissolved"] * 1000

nitrogen["Unit Symbol"] = nitrogen["Unit Symbol"].str.replace("m","µ")
nitrogen.head(10)"""

'nitrogen["Sampling Timestamp"] = pd.to_datetime(\n    nitrogen["Sampling Timestamp"], errors="coerce"\n)\n\n# drop unnecessary columns\nnitrogen = nitrogen.drop(columns=[\n    "Sample Timestamp",\n    "Station Name",\n    "Depth",\n    "Sampling Number",\n    "Sample Number"\n])\nnitrogen ["Nitrogen Dissolved"] = nitrogen["Nitrogen Dissolved"] * 1000\n\nnitrogen["Unit Symbol"] = nitrogen["Unit Symbol"].str.replace("m","µ")\nnitrogen.head(10)'

In [8]:
phosphorus["Sampling Timestamp"] = pd.to_datetime(
    phosphorus["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
phosphorus = phosphorus.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
phosphorus ["Phosphorus Total Dissolved"] = phosphorus["Phosphorus Total Dissolved"] * 1000

phosphorus["Unit Symbol"] = phosphorus["Unit Symbol"].str.replace("m","µ")

phosphorus.head(5)

,Sampling Timestamp,Phosphorus Total Dissolved,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2000-09-06 12:40:00,26.0,WHITESAND LAKE,'---,µg/l,3626,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.001,Centre,EUPHOTIC COMPOSITE
1,2001-10-04 13:06:00,28.0,WHITESAND LAKE,'---,µg/l,3626,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.001,Centre,VERTICAL INTEGRATED
2,2002-10-09 14:00:00,28.0,WHITESAND LAKE,'---,µg/l,3626,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.001,Centre,DISCRETE SAMPLE (GRAB)
3,2003-08-29 13:45:00,31.0,WHITESAND LAKE,'---,µg/l,3626,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.001,Centre,DISCRETE SAMPLE (GRAB)
4,2004-08-29 15:10:00,26.0,WHITESAND LAKE,'---,µg/l,3626,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.001,Centre,SINGLE EUPHOTIC COMPOSITE

In [9]:
vanadium["Sampling Timestamp"] = pd.to_datetime(
    vanadium["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
vanadium = vanadium.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
vanadium.head(10)

C:\Users\morsal.n\AppData\Local\Temp\ipykernel_34616\1651073378.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  vanadium["Sampling Timestamp"] = pd.to_datetime(

,Sampling Timestamp,Vanadium Dissolved,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2003-08-29 13:45:00,0.600,WHITESAND LAKE,'---,µg/l,2837,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,DISCRETE SAMPLE (GRAB)
1,2004-08-29 15:10:00,0.352,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
2,2007-08-27 12:30:00,0.396,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,DISCRETE SAMPLE (GRAB)
3,2008-09-02 14:00:00,0.610,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,DISCRETE SAMPLE (GRAB)
4,2009-08-16 12:30:00,0.676,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,DISCRETE SAMPLE (GRAB)
5,2010-08-30 12:30:00,0.605,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.10,Centre,DISCRETE SAMPLE (GRAB)
6,2011-08-31 11:30:00,0.564,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.10,Centre,DISCRETE SAMPLE (GRAB)
7,2012-08-27 13:15:00,0.371,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.10,Centre,SINGLE EUPHOTIC COMPOSITE
8,2013-09-05 12:20:00,0.569,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.10,Centre,DISCRETE SAMPLE (GRAB)
9,2015-08-25 13:00:00,0.460,WHITESAND LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.02,Centre,SINGLE EUPHOTIC COMPOSITE

In [18]:
"""
aluminum = aluminum.set_index("Sampling Timestamp")
calcium = calcium.set_index("Sampling Timestamp")
copper = copper.set_index("Sampling Timestamp")
lead = lead.set_index("Sampling Timestamp")
nickle = nickle.set_index("Sampling Timestamp")
phosphorus = phosphorus.set_index("Sampling Timestamp")
vanadium = vanadium.set_index("Sampling Timestamp")
"""
aluminum = aluminum.reset_index()
calcium = calcium.reset_index()
copper = copper.reset_index()
lead = lead.reset_index()
nickle = nickle.reset_index()
phosphorus = phosphorus.reset_index()
vanadium = vanadium.reset_index()

In [26]:

import numpy as np
aluminum_df = aluminum[["Sampling Timestamp", "Aluminum Dissolved"]]
calcium_df = calcium[["Sampling Timestamp", "Calcium Dissolved"]]
copper_df = copper[["Sampling Timestamp", "Copper Dissolved"]]
lead_df = lead[["Sampling Timestamp", "Lead Dissolved"]]
nickle_df = nickle[["Sampling Timestamp", "Nickel Dissolved"]]
phosphorus_df = phosphorus[["Sampling Timestamp", "Phosphorus Total Dissolved"]]
vanadium_df = vanadium[["Sampling Timestamp", "Vanadium Dissolved"]]

df = pd.concat(
    [
        aluminum_df,
        calcium_df,
        copper_df,
        lead_df,
        nickle_df,
        phosphorus_df,
        vanadium_df
    ],
    axis=0
)

In [28]:
df1= df.groupby("Sampling Timestamp", as_index=False).first()
df1

,Sampling Timestamp,Aluminum Dissolved,Calcium Dissolved,Copper Dissolved,Lead Dissolved,Nickel Dissolved,Phosphorus Total Dissolved,Vanadium Dissolved
0,2000-09-06 12:40:00,NaN,6590.0,NaN,NaN,NaN,26.0,NaN
1,2001-10-04 13:06:00,NaN,6210.0,NaN,NaN,NaN,28.0,NaN
2,2002-10-09 14:00:00,NaN,5230.0,NaN,NaN,NaN,28.0,NaN
3,2003-08-29 13:45:00,78.3,5350.0,1.200,0.1890,0.770,31.0,0.600
4,2004-08-29 15:10:00,64.5,4870.0,0.893,0.1010,0.977,26.0,0.352
5,2005-09-08 11:30:00,NaN,7760.0,NaN,NaN,NaN,19.0,NaN
6,2006-08-25 11:05:00,NaN,5590.0,NaN,NaN,NaN,25.0,NaN
7,2007-08-27 12:30:00,62.7,4800.0,0.446,0.0545,0.833,27.0,0.396
8,2008-09-02 14:00:00,98.3,4190.0,0.927,0.1720,0.914,38.0,0.610
9,2009-08-16 12:30:00,128.0,4420.0,0.844,0.1780,0.995,29.0,0.676
10,2010-08-30 12:30:00,115.0,4870.0,0.725,0.1510,0.951,30.0,0.605
11,2011-08-31 11:30:00,90.3,5090.0,1.400,0.2990,0.912,31.0,0.564
12,2012-08-27 13:15:00,69.7,6400.0,0.785,0.0800,0.865,16.0,0.371
13,2013-09-05 12:20:00,144.0,5900.0,0.838,0.1280,1.180,26.0,0.569
14,2015-08-25 13:00:00,75.9,5420.0,0.660,0.1170,0.841,25.0,0.460
15,2016-08-24 11:20:00,99.3,5920.0,0.780,0.1410,0.990,24.0,0.480
16,2017-08-21 12:45:00,73.2,6850.0,0.680,0.1100,1.130,31.0,0.437
17,2020-09-14 12:45:00,124.0,4900.0,0.700,0.0600,1.330,3.0,0.249
18,2021-08-17 12:20:00,102.0,4100.0,0.860,0.0800,1.220,20.0,0.355
19,2022-09-12 11:30:00,0.9,300.0,0.080,0.0200,0.030,3.0,0.006

In [ ]:
#df.to_csv("whiteSand_Data.csv", index = True)