In [67]:
import pandas as pd
FarLakes = pd.read_csv("FarLakes_Data.csv")
MidLakes = pd.read_csv("MidLake_Data.csv")
NearLakes = pd.read_csv("NearLake_Data.csv")

In [20]:
NearLakes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   sampling_timestamp             51 non-null     object
 1   Aluminum Dissolved             37 non-null     float64
 2   Aluminum Total Recoverable     39 non-null     float64
 3   Calcium Dissolved              51 non-null     float64
 4   Calcium Total                  37 non-null     float64
 5   Copper Dissolved               37 non-null     float64
 6   Copper Total Recoverable       39 non-null     float64
 7   Lead Dissolved                 37 non-null     float64
 8   Lead Total Recoverable         39 non-null     float64
 9   Nickel Dissolved               37 non-null     float64
 10  Nickel Total Recoverable       39 non-null     float64
 11  Nitrogen Dissolved             21 non-null     float64
 12  Phosphorus Total Dissolved     51 non-null     float64
 13  Phosphorus Total               51 non-null     float64
 14  Vanadium Dissolved             37 non-null     float64
 15  Turbidity                      27 non-null     float64
 16  pH                             51 non-null     float64
 17  Oxygen dissolved % saturation  5 non-null      float64
 18  OXYGEN BIOCHEMICAL DEMAND      17 non-null     float64
 19  Site Name                      51 non-null     object
 20  Unit Symbol                    51 non-null     object
 21  Nitrogen Total                 8 non-null      float64
 22  Distance Group                 51 non-null     object
dtypes: float64(19), object(4)
memory usage: 9.3+ KB

In [68]:
df = pd.concat([FarLakes, MidLakes, NearLakes])

In [69]:
df["Sampling Timestamp"] = df["Sampling Timestamp"].fillna(df["sampling_timestamp"])
df = df.drop(columns=["sampling_timestamp"])

In [70]:
df["Sampling Timestamp"] = pd.to_datetime(
    df["Sampling Timestamp"], errors="coerce"
)
df = df.sort_values(by="Sampling Timestamp")

In [71]:
df = df.groupby(
    ["Site Name","Sampling Timestamp"],
    as_index=False
).max()

In [72]:
df

,Site Name,Sampling Timestamp,Aluminum Dissolved,Aluminum Total Recoverable,Calcium Dissolved,Calcium Total,Copper Dissolved,Copper Total Recoverable,Lead Dissolved,Lead Total Recoverable,...,Phosphorus Total,Vanadium Dissolved,Turbidity,pH,Oxygen dissolved % saturation,OXYGEN BIOCHEMICAL DEMAND,Unit Symbol,Distance Group,Nitrogen Total,Vanadium Total Recoverable
0,Kearl LAKE,2000-09-27 12:00:00,NaN,NaN,20300.0,NaN,NaN,NaN,NaN,NaN,...,11.0,NaN,NaN,8.00,NaN,NaN,µg/l,Near-Fields,NaN,NaN
1,Kearl LAKE,2001-09-13 12:00:00,NaN,NaN,19600.0,NaN,NaN,NaN,NaN,NaN,...,13.0,NaN,NaN,7.90,NaN,NaN,µg/l,Near-Fields,NaN,NaN
2,Kearl LAKE,2002-09-04 12:00:00,NaN,NaN,20600.0,NaN,NaN,NaN,NaN,NaN,...,9.0,NaN,NaN,7.70,NaN,NaN,µg/l,Near-Fields,NaN,NaN
3,Kearl LAKE,2003-03-24 12:00:00,6.00,19.4,37800.0,38600.0,5.40,7.70,1.200,1.700,...,15.0,0.40,NaN,7.80,1.8,2000.0,µg/l,Near-Fields,NaN,NaN
4,Kearl LAKE,2003-08-31 12:00:00,NaN,NaN,16900.0,NaN,NaN,NaN,NaN,NaN,...,23.0,NaN,8.3,7.94,NaN,NaN,µg/l,Near-Fields,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,gregoire LAKE,2015-03-02 12:00:00,4.79,259.0,33000.0,31000.0,0.45,0.68,0.011,0.094,...,38.1,0.14,NaN,7.74,NaN,2000.0,µg/l,Near-Fields,634.0,NaN
208,gregoire LAKE,2016-03-10 12:00:00,2.85,239.0,50200.0,50400.0,0.55,0.56,0.046,0.100,...,41.0,0.18,4.5,7.79,NaN,2000.0,µg/l,Near-Fields,1200.0,NaN
209,gregoire LAKE,2016-07-20 12:00:00,40.00,519.0,28600.0,28700.0,0.94,1.26,0.092,0.332,...,62.0,0.58,13.0,8.11,NaN,NaN,µg/l,Near-Fields,790.0,NaN
210,gregoire LAKE,2016-09-21 12:00:00,25.40,534.0,25500.0,26100.0,1.20,1.22,0.102,0.538,...,72.0,0.36,15.0,8.12,NaN,NaN,µg/l,Near-Fields,790.0,NaN
211,gregoire LAKE,2017-03-15 12:00:00,8.91,96.2,40500.0,41700.0,0.61,0.85,0.025,0.149,...,41.0,0.15,7.8,7.84,NaN,NaN,µg/l,Near-Fields,890.0,NaN

In [74]:
#df["Sampling Date"] = df["Sampling Timestamp"].dt.date
lastcol = df.columns[-1]
move = df.pop(lastcol)
df.insert(1,lastcol,move)
df

,Site Name,Sampling Date,Sampling Timestamp,Aluminum Dissolved,Aluminum Total Recoverable,Calcium Dissolved,Calcium Total,Copper Dissolved,Copper Total Recoverable,Lead Dissolved,...,Phosphorus Total,Vanadium Dissolved,Turbidity,pH,Oxygen dissolved % saturation,OXYGEN BIOCHEMICAL DEMAND,Unit Symbol,Distance Group,Nitrogen Total,Vanadium Total Recoverable
0,Kearl LAKE,2000-09-27,2000-09-27 12:00:00,NaN,NaN,20300.0,NaN,NaN,NaN,NaN,...,11.0,NaN,NaN,8.00,NaN,NaN,µg/l,Near-Fields,NaN,NaN
1,Kearl LAKE,2001-09-13,2001-09-13 12:00:00,NaN,NaN,19600.0,NaN,NaN,NaN,NaN,...,13.0,NaN,NaN,7.90,NaN,NaN,µg/l,Near-Fields,NaN,NaN
2,Kearl LAKE,2002-09-04,2002-09-04 12:00:00,NaN,NaN,20600.0,NaN,NaN,NaN,NaN,...,9.0,NaN,NaN,7.70,NaN,NaN,µg/l,Near-Fields,NaN,NaN
3,Kearl LAKE,2003-03-24,2003-03-24 12:00:00,6.00,19.4,37800.0,38600.0,5.40,7.70,1.200,...,15.0,0.40,NaN,7.80,1.8,2000.0,µg/l,Near-Fields,NaN,NaN
4,Kearl LAKE,2003-08-31,2003-08-31 12:00:00,NaN,NaN,16900.0,NaN,NaN,NaN,NaN,...,23.0,NaN,8.3,7.94,NaN,NaN,µg/l,Near-Fields,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,gregoire LAKE,2015-03-02,2015-03-02 12:00:00,4.79,259.0,33000.0,31000.0,0.45,0.68,0.011,...,38.1,0.14,NaN,7.74,NaN,2000.0,µg/l,Near-Fields,634.0,NaN
208,gregoire LAKE,2016-03-10,2016-03-10 12:00:00,2.85,239.0,50200.0,50400.0,0.55,0.56,0.046,...,41.0,0.18,4.5,7.79,NaN,2000.0,µg/l,Near-Fields,1200.0,NaN
209,gregoire LAKE,2016-07-20,2016-07-20 12:00:00,40.00,519.0,28600.0,28700.0,0.94,1.26,0.092,...,62.0,0.58,13.0,8.11,NaN,NaN,µg/l,Near-Fields,790.0,NaN
210,gregoire LAKE,2016-09-21,2016-09-21 12:00:00,25.40,534.0,25500.0,26100.0,1.20,1.22,0.102,...,72.0,0.36,15.0,8.12,NaN,NaN,µg/l,Near-Fields,790.0,NaN
211,gregoire LAKE,2017-03-15,2017-03-15 12:00:00,8.91,96.2,40500.0,41700.0,0.61,0.85,0.025,...,41.0,0.15,7.8,7.84,NaN,NaN,µg/l,Near-Fields,890.0,NaN

In [75]:
df.drop(columns = ["Sampling Timestamp"], inplace = True)
df

,Site Name,Sampling Date,Aluminum Dissolved,Aluminum Total Recoverable,Calcium Dissolved,Calcium Total,Copper Dissolved,Copper Total Recoverable,Lead Dissolved,Lead Total Recoverable,...,Phosphorus Total,Vanadium Dissolved,Turbidity,pH,Oxygen dissolved % saturation,OXYGEN BIOCHEMICAL DEMAND,Unit Symbol,Distance Group,Nitrogen Total,Vanadium Total Recoverable
0,Kearl LAKE,2000-09-27,NaN,NaN,20300.0,NaN,NaN,NaN,NaN,NaN,...,11.0,NaN,NaN,8.00,NaN,NaN,µg/l,Near-Fields,NaN,NaN
1,Kearl LAKE,2001-09-13,NaN,NaN,19600.0,NaN,NaN,NaN,NaN,NaN,...,13.0,NaN,NaN,7.90,NaN,NaN,µg/l,Near-Fields,NaN,NaN
2,Kearl LAKE,2002-09-04,NaN,NaN,20600.0,NaN,NaN,NaN,NaN,NaN,...,9.0,NaN,NaN,7.70,NaN,NaN,µg/l,Near-Fields,NaN,NaN
3,Kearl LAKE,2003-03-24,6.00,19.4,37800.0,38600.0,5.40,7.70,1.200,1.700,...,15.0,0.40,NaN,7.80,1.8,2000.0,µg/l,Near-Fields,NaN,NaN
4,Kearl LAKE,2003-08-31,NaN,NaN,16900.0,NaN,NaN,NaN,NaN,NaN,...,23.0,NaN,8.3,7.94,NaN,NaN,µg/l,Near-Fields,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,gregoire LAKE,2015-03-02,4.79,259.0,33000.0,31000.0,0.45,0.68,0.011,0.094,...,38.1,0.14,NaN,7.74,NaN,2000.0,µg/l,Near-Fields,634.0,NaN
208,gregoire LAKE,2016-03-10,2.85,239.0,50200.0,50400.0,0.55,0.56,0.046,0.100,...,41.0,0.18,4.5,7.79,NaN,2000.0,µg/l,Near-Fields,1200.0,NaN
209,gregoire LAKE,2016-07-20,40.00,519.0,28600.0,28700.0,0.94,1.26,0.092,0.332,...,62.0,0.58,13.0,8.11,NaN,NaN,µg/l,Near-Fields,790.0,NaN
210,gregoire LAKE,2016-09-21,25.40,534.0,25500.0,26100.0,1.20,1.22,0.102,0.538,...,72.0,0.36,15.0,8.12,NaN,NaN,µg/l,Near-Fields,790.0,NaN
211,gregoire LAKE,2017-03-15,8.91,96.2,40500.0,41700.0,0.61,0.85,0.025,0.149,...,41.0,0.15,7.8,7.84,NaN,NaN,µg/l,Near-Fields,890.0,NaN

In [76]:
df_fixdate = df.groupby(
    ["Site Name","Sampling Date"],
    as_index=False
).max()

In [77]:
df_fixdate

,Site Name,Sampling Date,Aluminum Dissolved,Aluminum Total Recoverable,Calcium Dissolved,Calcium Total,Copper Dissolved,Copper Total Recoverable,Lead Dissolved,Lead Total Recoverable,...,Phosphorus Total,Vanadium Dissolved,Turbidity,pH,Oxygen dissolved % saturation,OXYGEN BIOCHEMICAL DEMAND,Unit Symbol,Distance Group,Nitrogen Total,Vanadium Total Recoverable
0,Kearl LAKE,2000-09-27,NaN,NaN,20300.0,NaN,NaN,NaN,NaN,NaN,...,11.0,NaN,NaN,8.00,NaN,NaN,µg/l,Near-Fields,NaN,NaN
1,Kearl LAKE,2001-09-13,NaN,NaN,19600.0,NaN,NaN,NaN,NaN,NaN,...,13.0,NaN,NaN,7.90,NaN,NaN,µg/l,Near-Fields,NaN,NaN
2,Kearl LAKE,2002-09-04,NaN,NaN,20600.0,NaN,NaN,NaN,NaN,NaN,...,9.0,NaN,NaN,7.70,NaN,NaN,µg/l,Near-Fields,NaN,NaN
3,Kearl LAKE,2003-03-24,6.00,19.4,37800.0,38600.0,5.40,7.70,1.200,1.700,...,15.0,0.40,NaN,7.80,1.8,2000.0,µg/l,Near-Fields,NaN,NaN
4,Kearl LAKE,2003-08-31,NaN,NaN,16900.0,NaN,NaN,NaN,NaN,NaN,...,23.0,NaN,8.3,7.94,NaN,NaN,µg/l,Near-Fields,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,gregoire LAKE,2015-03-02,4.79,259.0,33000.0,31000.0,0.45,0.68,0.011,0.094,...,38.1,0.14,NaN,7.74,NaN,2000.0,µg/l,Near-Fields,634.0,NaN
117,gregoire LAKE,2016-03-10,2.85,239.0,50200.0,50400.0,0.55,0.56,0.046,0.100,...,41.0,0.18,4.5,7.79,NaN,2000.0,µg/l,Near-Fields,1200.0,NaN
118,gregoire LAKE,2016-07-20,40.00,519.0,28600.0,28700.0,0.94,1.26,0.092,0.332,...,62.0,0.58,13.0,8.11,NaN,NaN,µg/l,Near-Fields,790.0,NaN
119,gregoire LAKE,2016-09-21,25.40,534.0,25500.0,26100.0,1.20,1.22,0.102,0.538,...,72.0,0.36,15.0,8.12,NaN,NaN,µg/l,Near-Fields,790.0,NaN
120,gregoire LAKE,2017-03-15,8.91,96.2,40500.0,41700.0,0.61,0.85,0.025,0.149,...,41.0,0.15,7.8,7.84,NaN,NaN,µg/l,Near-Fields,890.0,NaN

In [78]:
df_fixeddate.isna().mean().sort_values()

Sampling Timestamp               0.000000
Site Name                        0.000000
Distance Group                   0.000000
Unit Symbol                      0.000000
Calcium Dissolved                0.459184
Phosphorus Total                 0.459184
Phosphorus Total Dissolved       0.459184
Aluminum Total Recoverable       0.556122
pH                               0.561224
Nickel Total Recoverable         0.566327
Lead Total Recoverable           0.571429
Lead Dissolved                   0.576531
Copper Total Recoverable         0.576531
Vanadium Dissolved               0.576531
Nickel Dissolved                 0.586735
Copper Dissolved                 0.586735
Calcium Total                    0.591837
Aluminum Dissolved               0.596939
Turbidity                        0.714286
Nitrogen Dissolved               0.755102
Nitrogen Total                   0.801020
Vanadium Total Recoverable       0.882653
OXYGEN BIOCHEMICAL DEMAND        0.897959
Oxygen dissolved % saturation    0.959184
dtype: float64

In [79]:
mid_lakes = df_fixdate[df_fixeddate["Distance Group"] == "Mid-Fields"]

mid_lakes

C:\Users\morsal.n\AppData\Local\Temp\ipykernel_21576\153804777.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  mid_lakes = df_fixdate[df_fixeddate["Distance Group"] == "Mid-Fields"]

,Site Name,Sampling Date,Aluminum Dissolved,Aluminum Total Recoverable,Calcium Dissolved,Calcium Total,Copper Dissolved,Copper Total Recoverable,Lead Dissolved,Lead Total Recoverable,...,Phosphorus Total,Vanadium Dissolved,Turbidity,pH,Oxygen dissolved % saturation,OXYGEN BIOCHEMICAL DEMAND,Unit Symbol,Distance Group,Nitrogen Total,Vanadium Total Recoverable
8,Kearl LAKE,2004-08-24,0.94,12.7,16600.0,18100.0,0.118,0.166,0.0059,0.0314,...,27.0,0.201,1.50,8.04,NaN,NaN,µg/l,Near-Fields,NaN,NaN
9,Kearl LAKE,2004-09-25,NaN,NaN,17200.0,NaN,NaN,NaN,NaN,NaN,...,28.0,NaN,NaN,7.98,NaN,NaN,µg/l,Near-Fields,NaN,NaN
10,Kearl LAKE,2005-04-07,NaN,NaN,21600.0,NaN,NaN,NaN,NaN,NaN,...,17.0,NaN,1.45,7.49,NaN,NaN,µg/l,Near-Fields,NaN,NaN
11,Kearl LAKE,2005-05-26,NaN,NaN,12400.0,NaN,NaN,NaN,NaN,NaN,...,20.0,NaN,NaN,7.82,NaN,NaN,µg/l,Near-Fields,NaN,NaN
14,Kearl LAKE,2005-08-30,NaN,14.0,27570.0,15200.0,NaN,0.200,NaN,0.0485,...,22.0,NaN,1.50,8.00,NaN,NaN,µg/l,Near-Fields,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,gregoire LAKE,2015-03-02,4.79,259.0,33000.0,31000.0,0.450,0.680,0.0110,0.0940,...,38.1,0.140,NaN,7.74,NaN,2000.0,µg/l,Near-Fields,634.0,NaN
117,gregoire LAKE,2016-03-10,2.85,239.0,50200.0,50400.0,0.550,0.560,0.0460,0.1000,...,41.0,0.180,4.50,7.79,NaN,2000.0,µg/l,Near-Fields,1200.0,NaN
118,gregoire LAKE,2016-07-20,40.00,519.0,28600.0,28700.0,0.940,1.260,0.0920,0.3320,...,62.0,0.580,13.00,8.11,NaN,NaN,µg/l,Near-Fields,790.0,NaN
119,gregoire LAKE,2016-09-21,25.40,534.0,25500.0,26100.0,1.200,1.220,0.1020,0.5380,...,72.0,0.360,15.00,8.12,NaN,NaN,µg/l,Near-Fields,790.0,NaN
120,gregoire LAKE,2017-03-15,8.91,96.2,40500.0,41700.0,0.610,0.850,0.0250,0.1490,...,41.0,0.150,7.80,7.84,NaN,NaN,µg/l,Near-Fields,890.0,NaN

In [80]:
df_fixdate.to_csv("CombinedLakes_Data03-17.csv", index= False)

In [35]:
df.groupby(["Site Name","Sampling Timestamp"]).size().sort_values(ascending=False)

Site Name        Sampling Timestamp
Kearl LAKE       2000-09-27 12:00:00    1
NAMUR LAKE       2016-07-19 12:00:00    1
                 2016-09-20 12:00:00    1
                 2017-03-14 12:00:00    1
                 2017-08-23 08:29:00    1
                                       ..
MCCLELLAND LAKE  2012-09-09 11:00:00    1
                 2012-09-09 12:00:00    1
                 2013-09-05 03:00:00    1
                 2013-09-05 07:00:00    1
gregoire LAKE    2017-03-15 12:00:00    1
Length: 212, dtype: int64