In [2]:
import pandas as pd

aluminum = pd.read_csv("NAMURLAKE_Aluminum.csv", encoding="latin1")
aluminum_total = pd.read_csv("NAMURLAKE_Aluminum_Total_recoverable.csv", encoding="latin1")

calcium = pd.read_csv("NAMURLAKE_Calcium.csv", encoding="latin1")
calcium_total = pd.read_csv("NAMURLAKE_Calcium_Total.csv", encoding="latin1")

copper = pd.read_csv("NAMURLAKE_Copper.csv", encoding="latin1")
copper_total = pd.read_csv("NAMURLAKE_Copper_Total_recoverable.csv", encoding="latin1")

lead = pd.read_csv("NAMURLAKE_Lead.csv", encoding="latin1")
lead_total = pd.read_csv("NAMURLAKE_Lead_Total_dissolved.csv", encoding="latin1")

nickle = pd.read_csv("NAMURLAKE_Nickle.csv", encoding="latin1")
nickle_total = pd.read_csv("NAMURLAKE_Nickle_total_recoverable.csv", encoding="latin1")

nitrogen = pd.read_csv("NAMURLAKE_Nitrogen.csv", encoding="latin1")

oxygen_bod = pd.read_csv("NAMURLAKE_Oxygen Biochemical Demand.csv", encoding="latin1")
oxygen_sat = pd.read_csv("NAMURLAKE_Oxygen dissolved % saturation.csv", encoding="latin1")

ph = pd.read_csv("NAMURLAKE_PH.csv", encoding="latin1")

phosphorus = pd.read_csv("NAMURLAKE_Phosphorus.csv", encoding="latin1")
phosphorus_total = pd.read_csv("NAMURLAKE_Phosphorus_total.csv", encoding="latin1")

turbidity = pd.read_csv("NAMURLAKE_Turbidity.csv", encoding="latin1")

vanadium = pd.read_csv("NAMURLAKE_Vanadium.csv", encoding="latin1")

In [3]:

# convert timestamp
aluminum["Sampling Timestamp"] = pd.to_datetime(
    aluminum["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
aluminum = aluminum.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])

# clean units
#aluminum["Unit Symbol"] = aluminum["Unit Symbol"].str.replace("u","µ")

In [4]:
"""aluminum_total["Sampling Timestamp"] = pd.to_datetime(
    aluminum_total["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
aluminum_total = aluminum_total.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])"""
aluminum_total.head(5)

,Sampling Timestamp,Aluminum Total Recoverable,Site Name,Station Name,Depth,Value Sign,Unit Symbol,Method,Laboratory,Sampling Number,Sample Number,RDL,Sample Location,Sample Type,Sample Timestamp
0,09/13/2001 10:45 AM,16.4,NAMUR LAKE,NAMUR LAKE,NaN,'---,µg/l,2845,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),01SWE03691,01SWE03122,NaN,Centre,SINGLE EUPHOTIC COMPOSITE,09/13/2001 11:00 AM
1,08/28/2003 8:55 AM,13.6,NAMUR LAKE,NAMUR LAKE,NaN,'---,µg/l,2845,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),03SWE01770,03SWE01770,NaN,Centre,SINGLE EUPHOTIC COMPOSITE,08/28/2003 7:55 AM
2,08/29/2004 8:45 AM,3.6,NAMUR LAKE,NAMUR LAKE,NaN,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),04SWE03018,04SWE02271,NaN,Centre,SINGLE EUPHOTIC COMPOSITE,08/29/2004 7:45 AM
3,08/27/2005 9:58 AM,4.7,NAMUR LAKE,NAMUR LAKE,NaN,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),05SWE02657,05SWE02658,NaN,Centre,SINGLE EUPHOTIC COMPOSITE,08/27/2005 8:58 AM
4,08/21/2006 12:10 PM,9.4,NAMUR LAKE,NAMUR LAKE,NaN,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),06SWE03292,06SWE01886,NaN,Centre,SINGLE EUPHOTIC COMPOSITE,08/21/2006 11:10 AM

In [5]:

calcium["Sampling Timestamp"] = pd.to_datetime(
    calcium["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
calcium = calcium.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])

calcium["Calcium Dissolved"] = calcium["Calcium Dissolved"] * 1000

calcium["Unit Symbol"] = calcium["Unit Symbol"].str.replace("m","µ")

calcium.head(10)

,Sampling Timestamp,Calcium Dissolved,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,1999-08-10 10:25:00,6130.0,NAMUR LAKE,'---,µg/l,482,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.003,Centre,EUPHOTIC COMPOSITE
1,2000-08-31 09:20:00,6470.0,NAMUR LAKE,'---,µg/l,482,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.003,Centre,EUPHOTIC COMPOSITE
2,2001-09-13 10:45:00,6280.0,NAMUR LAKE,'---,µg/l,482,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.003,Centre,SINGLE EUPHOTIC COMPOSITE
3,2002-10-01 12:00:00,6520.0,NAMUR LAKE,'---,µg/l,482,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.003,Centre,SINGLE EUPHOTIC COMPOSITE
4,2003-08-28 08:55:00,6530.0,NAMUR LAKE,'---,µg/l,482,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.003,Centre,SINGLE EUPHOTIC COMPOSITE
5,2004-08-29 08:45:00,6260.0,NAMUR LAKE,'---,µg/l,482,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.003,Centre,SINGLE EUPHOTIC COMPOSITE
6,2005-08-27 09:58:00,9600.0,NAMUR LAKE,'---,µg/l,482,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.003,Centre,SINGLE EUPHOTIC COMPOSITE
7,2006-08-21 12:10:00,6270.0,NAMUR LAKE,'---,µg/l,482,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.003,Centre,SINGLE EUPHOTIC COMPOSITE
8,2007-08-21 09:40:00,6350.0,NAMUR LAKE,'---,µg/l,482,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.003,Centre,SINGLE EUPHOTIC COMPOSITE
9,2008-08-27 10:05:00,6790.0,NAMUR LAKE,'---,µg/l,482,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.003,Centre,SINGLE EUPHOTIC COMPOSITE

In [6]:
calcium_total["Sampling Timestamp"] = pd.to_datetime(
    calcium_total["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
calcium_total = calcium_total.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])

calcium_total["Calcium Total"] = calcium_total["Calcium Total"] * 1000

calcium_total["Unit Symbol"] = calcium_total["Unit Symbol"].str.replace("m","µ")
calcium_total.head(5)

,Sampling Timestamp,Calcium Total,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2001-09-13 10:45:00,6500.0,NAMUR LAKE,'---,µg/l,2845,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
1,2003-08-28 08:55:00,6500.0,NAMUR LAKE,'---,µg/l,2845,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
2,2004-08-29 08:45:00,7120.0,NAMUR LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
3,2005-08-27 09:58:00,6650.0,NAMUR LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
4,2006-08-21 12:10:00,6480.0,NAMUR LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE

In [7]:
copper["Sampling Timestamp"] = pd.to_datetime(
    copper["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
copper = copper.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
copper.head(10)

,Sampling Timestamp,Copper Dissolved,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2003-08-28 08:55:00,0.300,NAMUR LAKE,'---,µg/l,2837,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
1,2004-08-29 08:45:00,0.453,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
2,2005-08-27 09:58:00,0.550,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
3,2007-08-21 09:40:00,0.290,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
4,2008-08-27 10:05:00,0.343,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
5,2009-08-19 10:30:00,0.287,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
6,2010-09-03 09:30:00,0.262,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.1,Centre,SINGLE EUPHOTIC COMPOSITE
7,2011-08-30 10:30:00,0.305,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.1,Centre,SINGLE EUPHOTIC COMPOSITE
8,2012-08-30 09:00:00,0.351,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.1,Centre,SINGLE EUPHOTIC COMPOSITE
9,2013-08-26 12:45:00,0.285,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.1,Centre,SINGLE EUPHOTIC COMPOSITE

In [8]:
copper_total["Sampling Timestamp"] = pd.to_datetime(
    copper_total["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
copper_total = copper_total.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
copper_total.head(10)

,Sampling Timestamp,Copper Total Recoverable,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2001-09-13 10:45:00,1.100,NAMUR LAKE,'---,µg/l,2845,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
1,2003-08-28 08:55:00,0.900,NAMUR LAKE,'---,µg/l,2845,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
2,2004-08-29 08:45:00,0.441,NAMUR LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
3,2005-08-27 09:58:00,0.555,NAMUR LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
4,2006-08-21 12:10:00,0.497,NAMUR LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
5,2007-08-21 09:40:00,0.320,NAMUR LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
6,2008-08-27 10:05:00,0.346,NAMUR LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
7,2009-08-19 10:30:00,0.290,NAMUR LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
8,2010-09-03 09:30:00,0.265,NAMUR LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.1,Centre,SINGLE EUPHOTIC COMPOSITE
9,2011-08-30 10:30:00,0.308,NAMUR LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.1,Centre,SINGLE EUPHOTIC COMPOSITE

In [9]:
lead["Sampling Timestamp"] = pd.to_datetime(
    lead["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
lead = lead.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
lead.head(5)

,Sampling Timestamp,Lead Dissolved,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2003-08-28 08:55:00,0.0100,NAMUR LAKE,'---,µg/l,2837,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
1,2004-08-29 08:45:00,0.0069,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
2,2005-08-27 09:58:00,0.0136,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
3,2007-08-21 09:40:00,0.0154,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
4,2008-08-27 10:05:00,0.0115,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE

In [10]:
lead_total["Sampling Timestamp"] = pd.to_datetime(
    lead_total["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
lead_total = lead_total.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
lead_total.head(5)

,Sampling Timestamp,Lead Total Recoverable,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2001-09-13 10:45:00,0.5820,NAMUR LAKE,'---,µg/l,2845,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
1,2003-08-28 08:55:00,0.0880,NAMUR LAKE,'---,µg/l,2845,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
2,2004-08-29 08:45:00,0.0212,NAMUR LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
3,2005-08-27 09:58:00,0.0206,NAMUR LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
4,2006-08-21 12:10:00,0.1920,NAMUR LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE

In [11]:
nickle["Sampling Timestamp"] = pd.to_datetime(
    nickle["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
nickle = nickle.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
nickle.head(10)

,Sampling Timestamp,Nickel Dissolved,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2003-08-28 08:55:00,0.700,NAMUR LAKE,'---,µg/l,2840,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
1,2004-08-29 08:45:00,0.560,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
2,2005-08-27 09:58:00,0.570,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
3,2007-08-21 09:40:00,0.562,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
4,2008-08-27 10:05:00,0.724,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
5,2009-08-19 10:30:00,0.574,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
6,2010-09-03 09:30:00,0.524,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.1,Centre,SINGLE EUPHOTIC COMPOSITE
7,2011-08-30 10:30:00,0.548,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.1,Centre,SINGLE EUPHOTIC COMPOSITE
8,2012-08-30 09:00:00,0.492,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.1,Centre,SINGLE EUPHOTIC COMPOSITE
9,2013-08-26 12:45:00,0.593,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.1,Centre,SINGLE EUPHOTIC COMPOSITE

In [12]:
nickle_total["Sampling Timestamp"] = pd.to_datetime(
    nickle_total["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
nickle_total = nickle_total.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
nickle_total.head(10)

,Sampling Timestamp,Nickel Total Recoverable,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2001-09-13 10:45:00,0.600,NAMUR LAKE,'---,µg/l,2847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
1,2003-08-28 08:55:00,0.700,NAMUR LAKE,'---,µg/l,2847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
2,2004-08-29 08:45:00,0.620,NAMUR LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
3,2005-08-27 09:58:00,0.660,NAMUR LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
4,2006-08-21 12:10:00,0.575,NAMUR LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
5,2007-08-21 09:40:00,0.598,NAMUR LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
6,2008-08-27 10:05:00,0.762,NAMUR LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
7,2009-08-19 10:30:00,0.605,NAMUR LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
8,2010-09-03 09:30:00,0.561,NAMUR LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.1,Centre,SINGLE EUPHOTIC COMPOSITE
9,2011-08-30 10:30:00,0.639,NAMUR LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.1,Centre,SINGLE EUPHOTIC COMPOSITE

In [13]:
nitrogen["Sampling Timestamp"] = pd.to_datetime(
    nitrogen["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
nitrogen = nitrogen.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
nitrogen ["Nitrogen Dissolved"] = nitrogen["Nitrogen Dissolved"] * 1000

nitrogen["Unit Symbol"] = nitrogen["Unit Symbol"].str.replace("m","µ")
nitrogen.head(10)

,Sampling Timestamp,Nitrogen Dissolved,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,1999-08-10 10:25:00,258.0,NAMUR LAKE,'---,µg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.007,Centre,EUPHOTIC COMPOSITE
1,2000-08-31 09:20:00,340.0,NAMUR LAKE,'---,µg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.007,Centre,EUPHOTIC COMPOSITE
2,2001-09-13 10:45:00,297.0,NAMUR LAKE,'---,µg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.007,Centre,SINGLE EUPHOTIC COMPOSITE
3,2002-10-01 12:00:00,324.0,NAMUR LAKE,'---,µg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.007,Centre,SINGLE EUPHOTIC COMPOSITE
4,2003-08-28 08:55:00,271.0,NAMUR LAKE,'---,µg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.007,Centre,SINGLE EUPHOTIC COMPOSITE
5,2004-08-29 08:45:00,319.0,NAMUR LAKE,'---,µg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.007,Centre,SINGLE EUPHOTIC COMPOSITE
6,2005-08-27 09:58:00,258.0,NAMUR LAKE,'---,µg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.007,Centre,SINGLE EUPHOTIC COMPOSITE
7,2006-08-21 12:10:00,413.0,NAMUR LAKE,'---,µg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.007,Centre,SINGLE EUPHOTIC COMPOSITE
8,2007-08-21 09:40:00,273.0,NAMUR LAKE,'---,µg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.007,Centre,SINGLE EUPHOTIC COMPOSITE
9,2008-08-27 10:05:00,332.0,NAMUR LAKE,'---,µg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.007,Centre,SINGLE EUPHOTIC COMPOSITE

In [14]:
oxygen_bod["Sampling Timestamp"] = pd.to_datetime(
    oxygen_bod["Sampling Timestamp"], errors="coerce"
)

oxygen_bod = oxygen_bod.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
oxygen_bod.head(5)

,Sampling Timestamp,OXYGEN BIOCHEMICAL DEMAND,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2014-05-26 12:00:00,2,NAMUR LAKE,<,mg/l,331,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",2,'---,NaN
1,2014-07-10 12:00:00,2,NAMUR LAKE,<,mg/l,331,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",2,'---,NaN
2,2014-09-06 12:00:00,2,NAMUR LAKE,<,mg/l,331,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",2,'---,NaN
3,2015-03-03 12:00:00,2,NAMUR LAKE,<,mg/l,331,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",2,'---,NaN
4,2016-03-15 12:00:00,2,NAMUR LAKE,<,mg/l,331,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",2,'---,NaN

In [15]:
oxygen_sat["Sampling Timestamp"] = pd.to_datetime(
    oxygen_sat["Sampling Timestamp"], errors="coerce"
)

oxygen_sat = oxygen_sat.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
oxygen_sat.head(5)

,Sampling Timestamp,Oxygen dissolved % saturation,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2020-09-16 08:00:00,92.3,NAMUR LAKE,'---,%,3620,FIELD,NaN,Centre,DISCRETE SAMPLE (GRAB)
1,2020-09-16 08:00:00,92.0,NAMUR LAKE,'---,%,3620,FIELD,NaN,Centre,DISCRETE SAMPLE (GRAB)
2,2020-09-16 08:00:00,92.2,NAMUR LAKE,'---,%,3620,FIELD,NaN,Centre,DISCRETE SAMPLE (GRAB)
3,2020-09-16 08:00:00,92.2,NAMUR LAKE,'---,%,3620,FIELD,NaN,Centre,DISCRETE SAMPLE (GRAB)
4,2020-09-16 08:00:00,92.2,NAMUR LAKE,'---,%,3620,FIELD,NaN,Centre,DISCRETE SAMPLE (GRAB)

In [16]:
ph["Sampling Timestamp"] = pd.to_datetime(
    ph["Sampling Timestamp"], errors="coerce"
)

ph = ph.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
ph.head(5)

,Sampling Timestamp,pH,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,1999-08-10 10:25:00,6.86,NAMUR LAKE,'---,'---,389,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,NaN,Centre,EUPHOTIC COMPOSITE
1,2000-08-31 09:20:00,7.09,NAMUR LAKE,'---,'---,389,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,NaN,Centre,EUPHOTIC COMPOSITE
2,2001-09-13 10:45:00,7.29,NAMUR LAKE,'---,'---,389,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,NaN,Centre,SINGLE EUPHOTIC COMPOSITE
3,2002-10-01 12:00:00,7.12,NAMUR LAKE,'---,'---,389,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,NaN,Centre,SINGLE EUPHOTIC COMPOSITE
4,2003-08-28 08:55:00,7.18,NAMUR LAKE,'---,'---,389,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,NaN,Centre,SINGLE EUPHOTIC COMPOSITE

In [17]:
phosphorus["Sampling Timestamp"] = pd.to_datetime(
    phosphorus["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
phosphorus = phosphorus.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
phosphorus ["Phosphorus Total Dissolved"] = phosphorus["Phosphorus Total Dissolved"] * 1000

phosphorus["Unit Symbol"] = phosphorus["Unit Symbol"].str.replace("m","µ")

phosphorus.head(10)

,Sampling Timestamp,Phosphorus Total Dissolved,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,1999-08-10 10:25:00,8.0,NAMUR LAKE,'---,µg/l,3626,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.001,Centre,EUPHOTIC COMPOSITE
1,2000-08-31 09:20:00,10.0,NAMUR LAKE,'---,µg/l,3626,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.001,Centre,EUPHOTIC COMPOSITE
2,2001-09-13 10:45:00,11.0,NAMUR LAKE,'---,µg/l,3626,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.001,Centre,SINGLE EUPHOTIC COMPOSITE
3,2002-10-01 12:00:00,12.0,NAMUR LAKE,'---,µg/l,3626,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.001,Centre,SINGLE EUPHOTIC COMPOSITE
4,2003-08-28 08:55:00,8.0,NAMUR LAKE,'---,µg/l,3626,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.001,Centre,SINGLE EUPHOTIC COMPOSITE
5,2004-08-29 08:45:00,8.0,NAMUR LAKE,'---,µg/l,3626,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.001,Centre,SINGLE EUPHOTIC COMPOSITE
6,2005-08-27 09:58:00,11.0,NAMUR LAKE,'---,µg/l,3626,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.001,Centre,SINGLE EUPHOTIC COMPOSITE
7,2006-08-21 12:10:00,6.0,NAMUR LAKE,'---,µg/l,3626,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.001,Centre,SINGLE EUPHOTIC COMPOSITE
8,2007-08-21 09:40:00,4.0,NAMUR LAKE,'---,µg/l,3626,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.001,Centre,SINGLE EUPHOTIC COMPOSITE
9,2008-08-27 10:05:00,4.0,NAMUR LAKE,'---,µg/l,3626,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.001,Centre,SINGLE EUPHOTIC COMPOSITE

In [18]:
phosphorus_total["Sampling Timestamp"] = pd.to_datetime(
    phosphorus_total["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
phosphorus_total = phosphorus_total.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
phosphorus_total ["Phosphorus Total "] = phosphorus_total["Phosphorus Total"] * 1000

phosphorus_total["Unit Symbol"] = phosphorus_total["Unit Symbol"].str.replace("m","µ")

phosphorus_total.head(5)

,Sampling Timestamp,Phosphorus Total,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type,Phosphorus Total
0,1999-08-10 10:25:00,0.020,NAMUR LAKE,'---,µg/l,3627,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.001,Centre,EUPHOTIC COMPOSITE,20.0
1,2000-08-31 09:20:00,0.021,NAMUR LAKE,'---,µg/l,3627,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.001,Centre,EUPHOTIC COMPOSITE,21.0
2,2001-09-13 10:45:00,0.017,NAMUR LAKE,'---,µg/l,3627,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.001,Centre,SINGLE EUPHOTIC COMPOSITE,17.0
3,2002-10-01 12:00:00,0.030,NAMUR LAKE,'---,µg/l,3627,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.001,Centre,SINGLE EUPHOTIC COMPOSITE,30.0
4,2003-08-28 08:55:00,0.018,NAMUR LAKE,'---,µg/l,3627,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.001,Centre,SINGLE EUPHOTIC COMPOSITE,18.0

In [19]:
turbidity["Sampling Timestamp"] = pd.to_datetime(
    turbidity["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
turbidity = turbidity.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
turbidity.head(5)

,Sampling Timestamp,Turbidity,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,1999-08-10 10:25:00,0.50,NAMUR LAKE,'---,NTU,47,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,NaN,Centre,EUPHOTIC COMPOSITE
1,2000-08-31 09:20:00,0.80,NAMUR LAKE,'---,NTU,47,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,NaN,Centre,EUPHOTIC COMPOSITE
2,2001-09-13 10:45:00,0.68,NAMUR LAKE,'---,NTU,47,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,NaN,Centre,SINGLE EUPHOTIC COMPOSITE
3,2002-10-01 12:00:00,0.87,NAMUR LAKE,'---,NTU,47,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,NaN,Centre,SINGLE EUPHOTIC COMPOSITE
4,2003-08-28 08:55:00,0.65,NAMUR LAKE,'---,NTU,47,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,NaN,Centre,SINGLE EUPHOTIC COMPOSITE

In [20]:
vanadium["Sampling Timestamp"] = pd.to_datetime(
    vanadium["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
vanadium = vanadium.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
vanadium.head(10)

,Sampling Timestamp,Vanadium Dissolved,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2003-08-28 08:55:00,0.1000,NAMUR LAKE,'---,µg/l,2837,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
1,2004-08-29 08:45:00,0.0200,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
2,2005-08-27 09:58:00,0.0460,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
3,2007-08-21 09:40:00,0.0418,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
4,2008-08-27 10:05:00,0.0347,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
5,2009-08-19 10:30:00,0.0538,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,Centre,SINGLE EUPHOTIC COMPOSITE
6,2010-09-03 09:30:00,0.0417,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.1,Centre,SINGLE EUPHOTIC COMPOSITE
7,2011-08-30 10:30:00,0.0689,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.1,Centre,SINGLE EUPHOTIC COMPOSITE
8,2012-08-30 09:00:00,0.0591,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.1,Centre,SINGLE EUPHOTIC COMPOSITE
9,2013-08-26 12:45:00,0.0615,NAMUR LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.1,Centre,SINGLE EUPHOTIC COMPOSITE

In [21]:
aluminum_df = aluminum[["Sampling Timestamp", "Aluminum Dissolved"]]
aluminum_total_df = aluminum_total[["Sampling Timestamp", "Aluminum Total Recoverable"]]

calcium_df = calcium[["Sampling Timestamp", "Calcium Dissolved"]]
calcium_total_df = calcium_total[["Sampling Timestamp", "Calcium Total"]]

copper_df = copper[["Sampling Timestamp", "Copper Dissolved"]]
copper_total_df = copper_total[["Sampling Timestamp", "Copper Total Recoverable"]]

lead_df = lead[["Sampling Timestamp", "Lead Dissolved"]]
lead_total_df = lead_total[["Sampling Timestamp", "Lead Total Recoverable"]]

nickle_df = nickle[["Sampling Timestamp", "Nickel Dissolved"]]
nickle_total_df = nickle_total[["Sampling Timestamp", "Nickel Total Recoverable"]]

nitrogen_df = nitrogen[["Sampling Timestamp", "Nitrogen Dissolved"]]

phosphorus_df = phosphorus[["Sampling Timestamp", "Phosphorus Total Dissolved"]]
phosphorus_total_df = phosphorus_total[["Sampling Timestamp", "Phosphorus Total"]]

vanadium_df = vanadium[["Sampling Timestamp", "Vanadium Dissolved"]]

turbidity_df = turbidity[["Sampling Timestamp", "Turbidity"]]

ph_df = ph[["Sampling Timestamp", "pH"]]

oxygen_sat_df = oxygen_sat[["Sampling Timestamp", "Oxygen dissolved % saturation"]]

oxygen_bod_df = oxygen_bod[["Sampling Timestamp", "OXYGEN BIOCHEMICAL DEMAND"]]

In [22]:


df = pd.concat(
    [
        aluminum_df,
        aluminum_total_df,
        calcium_df,
        calcium_total_df,
        copper_df,
        copper_total_df,
        lead_df,
        lead_total_df,
        nickle_df,
        nickle_total_df,
        nitrogen_df,
        phosphorus_df,
        phosphorus_total_df,
        vanadium_df,
        turbidity_df,
        ph_df,
        oxygen_sat_df,
        oxygen_bod_df
    ],
    axis=0
)


df["Site Name"] = "NAMUR LAKE"
df["Unit Symbol"] = "µg/l"

df= df.groupby("Sampling Timestamp", as_index=False).first()

df["Sampling Timestamp"] = pd.to_datetime(
    df["Sampling Timestamp"], errors="coerce"
)

In [23]:
df = df.sort_values(by="Sampling Timestamp")
df.head(10)

,Sampling Timestamp,Aluminum Dissolved,Aluminum Total Recoverable,Calcium Dissolved,Calcium Total,Copper Dissolved,Copper Total Recoverable,Lead Dissolved,Lead Total Recoverable,Nickel Dissolved,...,Nitrogen Dissolved,Phosphorus Total Dissolved,Phosphorus Total,Vanadium Dissolved,Turbidity,pH,Oxygen dissolved % saturation,OXYGEN BIOCHEMICAL DEMAND,Site Name,Unit Symbol
0,1999-08-10 10:25:00,NaN,NaN,6130.0,NaN,NaN,NaN,NaN,NaN,NaN,...,258.0,8.0,0.020,NaN,0.50,6.86,NaN,NaN,NAMUR LAKE,µg/l
1,2000-08-31 09:20:00,NaN,NaN,6470.0,NaN,NaN,NaN,NaN,NaN,NaN,...,340.0,10.0,0.021,NaN,0.80,7.09,NaN,NaN,NAMUR LAKE,µg/l
2,2001-09-13 10:45:00,NaN,NaN,6280.0,6500.0,NaN,1.100,NaN,0.5820,NaN,...,297.0,11.0,0.017,NaN,0.68,7.29,NaN,NaN,NAMUR LAKE,µg/l
52,2001-09-13 10:45:00,NaN,16.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
3,2002-10-01 12:00:00,NaN,NaN,6520.0,NaN,NaN,NaN,NaN,NaN,NaN,...,324.0,12.0,0.030,NaN,0.87,7.12,NaN,NaN,NAMUR LAKE,µg/l
4,2003-08-28 08:55:00,1.60,NaN,6530.0,6500.0,0.300,0.900,0.0100,0.0880,0.70,...,271.0,8.0,0.018,0.10,0.65,7.18,NaN,NaN,NAMUR LAKE,µg/l
46,2003-08-28 08:55:00,NaN,13.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
5,2004-08-29 08:45:00,0.25,NaN,6260.0,7120.0,0.453,0.441,0.0069,0.0212,0.56,...,319.0,8.0,0.017,0.02,NaN,7.28,NaN,NaN,NAMUR LAKE,µg/l
47,2004-08-29 08:45:00,NaN,3.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
43,2005-08-27 09:58:00,NaN,4.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l

In [ ]:
df.info()

In [24]:
df.to_csv("NamurLake_Data.csv", index= False)

In [ ]:
df.describe()