In [5]:
import pandas as pd

aluminum = pd.read_csv("TOUCHWOODLAKE_Aluminium.csv", encoding="latin1")
aluminum_total = pd.read_csv("TOUCHWOODLAKE_Aluminum_Total_recoverable.csv", encoding = "latin1")

calcium = pd.read_csv("TOUCHWOODLAKE_Calcium.csv", encoding="latin1")

copper = pd.read_csv("TOUCHWOODLAKE_Copper.csv", encoding="latin1")
copper_total = pd.read_csv("TOUCHWOODLAKE_Copper_Total_recoverable.csv", encoding="latin1")

lead = pd.read_csv("TOUCHWOODLAKE_Lead.csv", encoding="latin1")
lead_total = pd.read_csv("TOUCHWOODLAKE_Lead_Total_Recoverable.csv", encoding="latin1")

nickle = pd.read_csv("TOUCHWOODLAKE_Nickle.csv", encoding="latin1")
nickle_total = pd.read_csv("TOUCHWOODLAKE_Nickle_total_recoverable.csv", encoding="latin1")

nitrogen = pd.read_csv("TOUCHWOODLAKE_Nitrogen.csv", encoding="latin1")

phosphorus = pd.read_csv("TOUCHWOODLAKE_Phosphorus.csv", encoding="latin1")
phosphorus_total = pd.read_csv("TOUCHWOODLAKE_Phosphorus_Total.csv", encoding="latin1")

vanadium = pd.read_csv("TOUCHWOODLAKE_Vanadium.csv", encoding="latin1")

oxygen_sat = pd.read_csv("TOUCHWOODLAKE_Oxygen dissolved saturation.csv", encoding="latin1")

ph = pd.read_csv("TOUCHWOODLAKE_pH.csv", encoding="latin1")

turbidity = pd.read_csv("TOUCHWOODLAKE_Turbidity.csv", encoding="latin1")

total_recoverable = pd.read_csv("TOUCHWOODLAKE_Total_Recoverable.csv", encoding="latin1")

In [2]:

#convert timestamp
aluminum["Sampling Timestamp"] = pd.to_datetime(aluminum["Sampling Timestamp"], errors="coerce")

# drop unnecessary columns
aluminum = aluminum.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
# clean units
#aluminum["Unit Symbol"] = aluminum["Unit Symbol"].str.replace("u","µ")"""
aluminum.head(5)

,Sampling Timestamp,Aluminum Dissolved,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2024-07-11 10:30:00,1.2,TOUCHWOOD LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.4,1,DISCRETE SAMPLE (GRAB)
1,2024-07-11 10:30:00,2.4,TOUCHWOOD LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.4,1,DISCRETE SAMPLE (GRAB)
2,2024-07-11 10:30:00,0.5,TOUCHWOOD LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.4,1,DISCRETE SAMPLE (GRAB)
3,2025-02-26 11:00:00,0.4,TOUCHWOOD LAKE,<,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.4,1,DISCRETE SAMPLE (GRAB)
4,2025-07-13 13:45:00,0.7,TOUCHWOOD LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.4,1,DISCRETE SAMPLE (GRAB)

In [6]:
aluminum_total["Sampling Timestamp"] = pd.to_datetime(
    aluminum_total["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
aluminum_total = aluminum_total.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
aluminum_total.head(5)

,Sampling Timestamp,Aluminum Total Recoverable,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2024-07-11 10:30:00,3.8,TOUCHWOOD LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.4,1,DISCRETE SAMPLE (GRAB)
1,2024-07-11 10:30:00,9.3,TOUCHWOOD LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.4,1,DISCRETE SAMPLE (GRAB)
2,2024-07-11 10:30:00,0.4,TOUCHWOOD LAKE,<,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.4,1,DISCRETE SAMPLE (GRAB)
3,2025-02-26 11:00:00,4.0,TOUCHWOOD LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.4,1,DISCRETE SAMPLE (GRAB)
4,2025-07-13 13:45:00,6.7,TOUCHWOOD LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.4,1,DISCRETE SAMPLE (GRAB)

In [3]:

calcium["Sampling Timestamp"] = pd.to_datetime(
    calcium["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
calcium = calcium.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])

calcium["Calcium Dissolved"] = calcium["Calcium Dissolved"] * 1000

calcium["Unit Symbol"] = calcium["Unit Symbol"].str.replace("m","µ")

calcium.head(5)

,Sampling Timestamp,Calcium Dissolved,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2024-07-11 10:30:00,34000.0,TOUCHWOOD LAKE,'---,µg/l,1516,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.3,1,DISCRETE SAMPLE (GRAB)
1,2024-07-11 10:30:00,34000.0,TOUCHWOOD LAKE,'---,µg/l,1516,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.3,1,DISCRETE SAMPLE (GRAB)
2,2024-07-11 10:30:00,300.0,TOUCHWOOD LAKE,<,µg/l,1516,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.3,1,DISCRETE SAMPLE (GRAB)
3,2024-08-20 13:27:00,32000.0,TOUCHWOOD LAKE,'---,µg/l,1516,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.3,1,DISCRETE SAMPLE (GRAB)
4,2024-09-27 11:45:00,31000.0,TOUCHWOOD LAKE,'---,µg/l,1516,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.3,1,DISCRETE SAMPLE (GRAB)

In [4]:
copper["Sampling Timestamp"] = pd.to_datetime(
    copper["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
copper = copper.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
copper.head(10)

,Sampling Timestamp,Copper Dissolved,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2024-07-11 10:30:00,0.13,TOUCHWOOD LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.08,1,DISCRETE SAMPLE (GRAB)
1,2024-07-11 10:30:00,0.10,TOUCHWOOD LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.08,1,DISCRETE SAMPLE (GRAB)
2,2024-07-11 10:30:00,0.08,TOUCHWOOD LAKE,<,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.08,1,DISCRETE SAMPLE (GRAB)
3,2025-02-26 11:00:00,0.08,TOUCHWOOD LAKE,<,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.08,1,DISCRETE SAMPLE (GRAB)
4,2025-07-13 13:45:00,0.10,TOUCHWOOD LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.08,1,DISCRETE SAMPLE (GRAB)
5,2025-07-13 13:45:00,0.08,TOUCHWOOD LAKE,<,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.08,1,DUPLICATE SAMPLE
6,2025-07-13 13:45:00,0.08,TOUCHWOOD LAKE,<,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.08,1,FIELD BLANK

In [8]:
copper_total["Sampling Timestamp"] = pd.to_datetime(
    copper_total["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
copper_total = copper_total.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
copper_total.head(10)

,Sampling Timestamp,Copper Total Recoverable,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2024-07-11 10:30:00,0.14,TOUCHWOOD LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.08,1,DISCRETE SAMPLE (GRAB)
1,2024-07-11 10:30:00,0.12,TOUCHWOOD LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.08,1,DISCRETE SAMPLE (GRAB)
2,2024-07-11 10:30:00,0.08,TOUCHWOOD LAKE,<,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.08,1,DISCRETE SAMPLE (GRAB)
3,2025-02-26 11:00:00,0.08,TOUCHWOOD LAKE,<,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.08,1,DISCRETE SAMPLE (GRAB)
4,2025-07-13 13:45:00,0.20,TOUCHWOOD LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.08,1,DISCRETE SAMPLE (GRAB)
5,2025-07-13 13:45:00,0.08,TOUCHWOOD LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.08,1,DUPLICATE SAMPLE
6,2025-07-13 13:45:00,0.08,TOUCHWOOD LAKE,<,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.08,1,FIELD BLANK

In [5]:
lead["Sampling Timestamp"] = pd.to_datetime(
    lead["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
lead = lead.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
lead.head(10)

,Sampling Timestamp,Lead Dissolved,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2024-07-11 10:30:00,0.02,TOUCHWOOD LAKE,<,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.02,1,DISCRETE SAMPLE (GRAB)
1,2024-07-11 10:30:00,0.02,TOUCHWOOD LAKE,<,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.02,1,DISCRETE SAMPLE (GRAB)
2,2024-07-11 10:30:00,0.02,TOUCHWOOD LAKE,<,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.02,1,DISCRETE SAMPLE (GRAB)
3,2025-02-26 11:00:00,0.02,TOUCHWOOD LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.02,1,DISCRETE SAMPLE (GRAB)
4,2025-07-13 13:45:00,0.02,TOUCHWOOD LAKE,<,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.02,1,DISCRETE SAMPLE (GRAB)
5,2025-07-13 13:45:00,0.02,TOUCHWOOD LAKE,<,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.02,1,DUPLICATE SAMPLE
6,2025-07-13 13:45:00,0.02,TOUCHWOOD LAKE,<,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.02,1,FIELD BLANK

In [9]:
lead_total["Sampling Timestamp"] = pd.to_datetime(
    lead_total["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
lead_total = lead_total.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
lead_total.head(5)

,Sampling Timestamp,Lead Total Recoverable,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2024-07-11 10:30:00,0.007,TOUCHWOOD LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.004,1,DISCRETE SAMPLE (GRAB)
1,2024-07-11 10:30:00,0.009,TOUCHWOOD LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.004,1,DISCRETE SAMPLE (GRAB)
2,2024-07-11 10:30:00,0.004,TOUCHWOOD LAKE,<,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.004,1,DISCRETE SAMPLE (GRAB)
3,2025-02-26 11:00:00,0.038,TOUCHWOOD LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.004,1,DISCRETE SAMPLE (GRAB)
4,2025-07-13 13:45:00,0.006,TOUCHWOOD LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.004,1,DISCRETE SAMPLE (GRAB)

In [6]:
nickle["Sampling Timestamp"] = pd.to_datetime(
    nickle["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
nickle = nickle.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
nickle.head(10)

,Sampling Timestamp,Nickel Dissolved,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2024-07-11 10:30:00,0.23,TOUCHWOOD LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.03,1,DISCRETE SAMPLE (GRAB)
1,2024-07-11 10:30:00,0.24,TOUCHWOOD LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.03,1,DISCRETE SAMPLE (GRAB)
2,2024-07-11 10:30:00,0.03,TOUCHWOOD LAKE,<,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.03,1,DISCRETE SAMPLE (GRAB)
3,2025-02-26 11:00:00,0.17,TOUCHWOOD LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.03,1,DISCRETE SAMPLE (GRAB)
4,2025-07-13 13:45:00,0.19,TOUCHWOOD LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.03,1,DISCRETE SAMPLE (GRAB)
5,2025-07-13 13:45:00,0.16,TOUCHWOOD LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.03,1,DUPLICATE SAMPLE
6,2025-07-13 13:45:00,0.03,TOUCHWOOD LAKE,<,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.03,1,FIELD BLANK

In [10]:
nickle_total["Sampling Timestamp"] = pd.to_datetime(
    nickle_total["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
nickle_total = nickle_total.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
nickle_total.head(10)

,Sampling Timestamp,Nickel Total Recoverable,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2024-07-11 10:30:00,0.24,TOUCHWOOD LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.03,1,DISCRETE SAMPLE (GRAB)
1,2024-07-11 10:30:00,0.22,TOUCHWOOD LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.03,1,DISCRETE SAMPLE (GRAB)
2,2024-07-11 10:30:00,0.03,TOUCHWOOD LAKE,<,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.03,1,DISCRETE SAMPLE (GRAB)
3,2025-02-26 11:00:00,0.22,TOUCHWOOD LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.03,1,DISCRETE SAMPLE (GRAB)
4,2025-07-13 13:45:00,0.30,TOUCHWOOD LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.03,1,DISCRETE SAMPLE (GRAB)
5,2025-07-13 13:45:00,0.24,TOUCHWOOD LAKE,'---,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.03,1,DUPLICATE SAMPLE
6,2025-07-13 13:45:00,0.03,TOUCHWOOD LAKE,<,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.03,1,FIELD BLANK

In [7]:
nitrogen["Sampling Timestamp"] = pd.to_datetime(
    nitrogen["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
nitrogen = nitrogen.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
nitrogen ["Nitrogen Dissolved"] = nitrogen["Nitrogen Dissolved"] * 1000

nitrogen["Unit Symbol"] = nitrogen["Unit Symbol"].str.replace("m","µ")
nitrogen.head(10)

,Sampling Timestamp,Nitrogen Dissolved,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2024-07-11 10:30:00,300.0,TOUCHWOOD LAKE,'---,µg/l,317,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.02,1,DISCRETE SAMPLE (GRAB)
1,2024-07-11 10:30:00,320.0,TOUCHWOOD LAKE,'---,µg/l,317,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.02,1,DISCRETE SAMPLE (GRAB)
2,2024-07-11 10:30:00,20.0,TOUCHWOOD LAKE,<,µg/l,317,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.02,1,DISCRETE SAMPLE (GRAB)
3,2024-08-20 13:27:00,310.0,TOUCHWOOD LAKE,'---,µg/l,317,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.02,1,DISCRETE SAMPLE (GRAB)
4,2024-09-27 11:45:00,370.0,TOUCHWOOD LAKE,'---,µg/l,317,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.02,1,DISCRETE SAMPLE (GRAB)
5,2025-02-26 11:00:00,600.0,TOUCHWOOD LAKE,'---,µg/l,317,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.02,1,DISCRETE SAMPLE (GRAB)
6,2025-03-25 09:00:00,420.0,TOUCHWOOD LAKE,'---,µg/l,317,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.02,1,DISCRETE SAMPLE (GRAB)
7,2025-06-22 12:00:00,510.0,TOUCHWOOD LAKE,'---,µg/l,317,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.02,1,DISCRETE SAMPLE (GRAB)
8,2025-07-13 13:45:00,390.0,TOUCHWOOD LAKE,'---,µg/l,317,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.02,1,DISCRETE SAMPLE (GRAB)
9,2025-07-13 13:45:00,330.0,TOUCHWOOD LAKE,'---,µg/l,317,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.02,1,DUPLICATE SAMPLE

In [12]:
oxygen_sat["Sampling Timestamp"] = pd.to_datetime(
    oxygen_sat["Sampling Timestamp"], errors="coerce"
)

oxygen_sat = oxygen_sat.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
oxygen_sat.head(5)

,Sampling Timestamp,Oxygen dissolved % saturation,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2024-07-11 10:30:00,NaN,TOUCHWOOD LAKE,'---,%,3620,FIELD,NaN,1,DISCRETE SAMPLE (GRAB)
1,2024-07-11 10:30:00,NaN,TOUCHWOOD LAKE,'---,%,3620,FIELD,NaN,1,DISCRETE SAMPLE (GRAB)
2,2024-07-11 10:30:00,NaN,TOUCHWOOD LAKE,'---,%,3620,FIELD,NaN,1,DISCRETE SAMPLE (GRAB)
3,2024-07-11 10:30:00,NaN,TOUCHWOOD LAKE,'---,%,3620,FIELD,NaN,1,DISCRETE SAMPLE (GRAB)
4,2024-07-11 10:30:00,NaN,TOUCHWOOD LAKE,'---,%,3620,FIELD,NaN,1,DISCRETE SAMPLE (GRAB)

In [13]:
ph["Sampling Timestamp"] = pd.to_datetime(
    ph["Sampling Timestamp"], errors="coerce"
)

ph = ph.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
ph.head(5)

,Sampling Timestamp,pH,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2024-07-11 10:30:00,8.46,TOUCHWOOD LAKE,'---,'---,389,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",NaN,1,DISCRETE SAMPLE (GRAB)
1,2024-07-11 10:30:00,8.44,TOUCHWOOD LAKE,'---,'---,389,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",NaN,1,DISCRETE SAMPLE (GRAB)
2,2024-07-11 10:30:00,5.10,TOUCHWOOD LAKE,'---,'---,389,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",NaN,1,DISCRETE SAMPLE (GRAB)
3,2024-08-20 13:27:00,8.61,TOUCHWOOD LAKE,'---,'---,389,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",NaN,1,DISCRETE SAMPLE (GRAB)
4,2024-09-27 11:45:00,8.33,TOUCHWOOD LAKE,'---,'---,389,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",NaN,1,DISCRETE SAMPLE (GRAB)

In [8]:
phosphorus["Sampling Timestamp"] = pd.to_datetime(
    phosphorus["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
phosphorus = phosphorus.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
phosphorus ["Phosphorus Total Dissolved"] = phosphorus["Phosphorus Total Dissolved"] * 1000

phosphorus["Unit Symbol"] = phosphorus["Unit Symbol"].str.replace("m","µ")

phosphorus.head(5)

,Sampling Timestamp,Phosphorus Total Dissolved,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2024-07-11 10:30:00,3.0,TOUCHWOOD LAKE,<,µg/l,443,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.003,1,DISCRETE SAMPLE (GRAB)
1,2024-07-11 10:30:00,3.0,TOUCHWOOD LAKE,<,µg/l,443,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.003,1,DISCRETE SAMPLE (GRAB)
2,2024-07-11 10:30:00,3.0,TOUCHWOOD LAKE,<,µg/l,443,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.003,1,DISCRETE SAMPLE (GRAB)
3,2024-08-20 13:27:00,3.0,TOUCHWOOD LAKE,<,µg/l,443,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.003,1,DISCRETE SAMPLE (GRAB)
4,2024-09-27 11:45:00,3.0,TOUCHWOOD LAKE,<,µg/l,443,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.003,1,DISCRETE SAMPLE (GRAB)

In [14]:
phosphorus_total["Sampling Timestamp"] = pd.to_datetime(
    phosphorus_total["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
phosphorus_total = phosphorus_total.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
phosphorus_total ["Phosphorus Total "] = phosphorus_total["Phosphorus Total"] * 1000

phosphorus_total["Unit Symbol"] = phosphorus_total["Unit Symbol"].str.replace("m","µ")

phosphorus_total.head(5)

,Sampling Timestamp,Phosphorus Total,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type,Phosphorus Total
0,2024-07-11 10:30:00,0.0072,TOUCHWOOD LAKE,'---,µg/l,443,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.003,1,DISCRETE SAMPLE (GRAB),7.2
1,2024-07-11 10:30:00,0.0070,TOUCHWOOD LAKE,'---,µg/l,443,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.003,1,DISCRETE SAMPLE (GRAB),7.0
2,2024-07-11 10:30:00,0.0030,TOUCHWOOD LAKE,<,µg/l,443,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.003,1,DISCRETE SAMPLE (GRAB),3.0
3,2024-08-20 13:27:00,0.0038,TOUCHWOOD LAKE,'---,µg/l,443,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.003,1,DISCRETE SAMPLE (GRAB),3.8
4,2024-09-27 11:45:00,0.0130,TOUCHWOOD LAKE,'---,µg/l,443,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.003,1,DISCRETE SAMPLE (GRAB),13.0

In [15]:
turbidity["Sampling Timestamp"] = pd.to_datetime(
    turbidity["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
turbidity = turbidity.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
turbidity.head(5)

,Sampling Timestamp,Turbidity,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2024-07-11 10:30:00,0.10,TOUCHWOOD LAKE,<,NTU,409,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.1,1,DISCRETE SAMPLE (GRAB)
1,2024-07-11 10:30:00,0.10,TOUCHWOOD LAKE,<,NTU,409,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.1,1,DISCRETE SAMPLE (GRAB)
2,2024-07-11 10:30:00,0.10,TOUCHWOOD LAKE,<,NTU,409,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.1,1,DISCRETE SAMPLE (GRAB)
3,2024-08-20 13:27:00,0.94,TOUCHWOOD LAKE,'---,NTU,409,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.1,1,DISCRETE SAMPLE (GRAB)
4,2024-09-27 11:45:00,2.10,TOUCHWOOD LAKE,'---,NTU,409,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",0.1,1,DISCRETE SAMPLE (GRAB)

In [9]:
vanadium["Sampling Timestamp"] = pd.to_datetime(
    vanadium["Sampling Timestamp"], errors="coerce"
)

# drop unnecessary columns
vanadium = vanadium.drop(columns=[
    "Sample Timestamp",
    "Station Name",
    "Depth",
    "Sampling Number",
    "Sample Number"
])
vanadium.head(10)

,Sampling Timestamp,Vanadium Dissolved,Site Name,Value Sign,Unit Symbol,Method,Laboratory,RDL,Sample Location,Sample Type
0,2024-07-11 10:30:00,0.115,TOUCHWOOD LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.006,1,DISCRETE SAMPLE (GRAB)
1,2024-07-11 10:30:00,0.088,TOUCHWOOD LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.006,1,DISCRETE SAMPLE (GRAB)
2,2024-07-11 10:30:00,0.006,TOUCHWOOD LAKE,<,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.006,1,DISCRETE SAMPLE (GRAB)
3,2025-02-26 11:00:00,0.078,TOUCHWOOD LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.006,1,DISCRETE SAMPLE (GRAB)
4,2025-07-13 13:45:00,0.078,TOUCHWOOD LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.006,1,DISCRETE SAMPLE (GRAB)
5,2025-07-13 13:45:00,0.123,TOUCHWOOD LAKE,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.006,1,DUPLICATE SAMPLE
6,2025-07-13 13:45:00,0.006,TOUCHWOOD LAKE,<,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.006,1,FIELD BLANK

In [18]:
aluminum_df = aluminum[["Sampling Timestamp", "Aluminum Dissolved"]]
aluminum_total_df = aluminum_total[["Sampling Timestamp", "Aluminum Total Recoverable"]]

calcium_df = calcium[["Sampling Timestamp", "Calcium Dissolved"]]

copper_df = copper[["Sampling Timestamp", "Copper Dissolved"]]
copper_total_df = copper_total[["Sampling Timestamp", "Copper Total Recoverable"]]

lead_df = lead[["Sampling Timestamp", "Lead Dissolved"]]
lead_total_df = lead_total[["Sampling Timestamp", "Lead Total Recoverable"]]

nickle_df = nickle[["Sampling Timestamp", "Nickel Dissolved"]]
nickle_total_df = nickle_total[["Sampling Timestamp", "Nickel Total Recoverable"]]

nitrogen_df = nitrogen[["Sampling Timestamp", "Nitrogen Dissolved"]]

phosphorus_df = phosphorus[["Sampling Timestamp", "Phosphorus Total Dissolved"]]
phosphorus_total_df = phosphorus_total[["Sampling Timestamp", "Phosphorus Total"]]

vanadium_df = vanadium[["Sampling Timestamp", "Vanadium Dissolved"]]

turbidity_df = turbidity[["Sampling Timestamp", "Turbidity"]]

ph_df = ph[["Sampling Timestamp", "pH"]]

oxygen_sat_df = oxygen_sat[["Sampling Timestamp", "Oxygen dissolved % saturation"]]

In [22]:
import numpy as np


df = pd.concat(
    [
        aluminum_df,
        aluminum_total_df,
        calcium_df,
        copper_df,
        copper_total_df,
        lead_df,
        lead_total_df,
        nickle_df,
        nickle_total_df,
        nitrogen_df,
        phosphorus_df,
        phosphorus_total_df,
        vanadium_df,
        turbidity_df,
        ph_df,
        oxygen_sat_df
    ],
    axis=0
)

df["Site Name"] = "Touchwood Lake "
df["Unit Symbol"] = "µg/l"
df= df.groupby("Sampling Timestamp", as_index=False).first()

df["Sampling Timestamp"] = pd.to_datetime(
    df["Sampling Timestamp"], errors="coerce"
)

In [23]:
df = df.sort_values(by="Sampling Timestamp")
df

,Sampling Timestamp,Aluminum Dissolved,Aluminum Total Recoverable,Calcium Dissolved,Copper Dissolved,Copper Total Recoverable,Lead Dissolved,Lead Total Recoverable,Nickel Dissolved,Nickel Total Recoverable,Nitrogen Dissolved,Phosphorus Total Dissolved,Phosphorus Total,Vanadium Dissolved,Turbidity,pH,Oxygen dissolved % saturation,Site Name,Unit Symbol
0,2024-07-11 10:30:00,NaN,3.8,NaN,NaN,0.14,NaN,0.007,NaN,0.24,NaN,NaN,0.0072,NaN,0.10,8.46,NaN,Touchwood Lake,µg/l
12,2024-07-11 10:30:00,1.2,NaN,34.0,0.13,NaN,0.02,NaN,0.23,NaN,0.30,0.0030,NaN,0.115,NaN,NaN,NaN,Touchwood Lake,µg/l
1,2024-08-20 13:27:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0038,NaN,0.94,8.61,NaN,Touchwood Lake,µg/l
15,2024-08-20 13:27:00,NaN,NaN,32.0,NaN,NaN,NaN,NaN,NaN,NaN,0.31,0.0030,NaN,NaN,NaN,NaN,NaN,Touchwood Lake,µg/l
17,2024-09-27 11:45:00,NaN,NaN,31.0,NaN,NaN,NaN,NaN,NaN,NaN,0.37,0.0030,NaN,NaN,NaN,NaN,NaN,Touchwood Lake,µg/l
2,2024-09-27 11:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0130,NaN,2.10,8.33,NaN,Touchwood Lake,µg/l
9,2025-02-26 11:00:00,0.4,NaN,34.0,0.08,NaN,0.02,NaN,0.17,NaN,0.60,0.0100,NaN,0.078,NaN,NaN,NaN,Touchwood Lake,µg/l
3,2025-02-26 11:00:00,NaN,4.0,NaN,NaN,0.08,NaN,0.038,NaN,0.22,NaN,NaN,0.0150,NaN,0.12,7.51,NaN,Touchwood Lake,µg/l
10,2025-03-25 09:00:00,NaN,NaN,41.0,NaN,NaN,NaN,NaN,NaN,NaN,0.42,0.0069,NaN,NaN,NaN,NaN,NaN,Touchwood Lake,µg/l
4,2025-03-25 09:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0140,NaN,4.80,7.82,NaN,Touchwood Lake,µg/l
5,2025-06-22 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0110,NaN,2.50,7.52,NaN,Touchwood Lake,µg/l
11,2025-06-22 12:00:00,NaN,NaN,34.0,NaN,NaN,NaN,NaN,NaN,NaN,0.51,0.0030,NaN,NaN,NaN,NaN,NaN,Touchwood Lake,µg/l
6,2025-07-13 13:45:00,NaN,6.7,NaN,NaN,0.20,NaN,0.006,NaN,0.30,NaN,NaN,0.0110,NaN,0.13,8.71,NaN,Touchwood Lake,µg/l
13,2025-07-13 13:45:00,0.7,NaN,34.0,0.10,NaN,0.02,NaN,0.19,NaN,0.39,0.0052,NaN,0.078,NaN,NaN,NaN,Touchwood Lake,µg/l
7,2025-08-10 11:56:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0030,NaN,0.18,8.63,NaN,Touchwood Lake,µg/l
14,2025-08-10 11:56:00,NaN,NaN,33.0,NaN,NaN,NaN,NaN,NaN,NaN,0.39,0.0030,NaN,NaN,NaN,NaN,NaN,Touchwood Lake,µg/l
16,2025-09-07 11:05:00,NaN,NaN,34.0,NaN,NaN,NaN,NaN,NaN,NaN,0.35,0.0030,NaN,NaN,NaN,NaN,NaN,Touchwood Lake,µg/l
8,2025-09-07 11:05:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0092,NaN,3.50,8.52,NaN,Touchwood Lake,µg/l

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18 entries, 0 to 8
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Sampling Timestamp             18 non-null     datetime64[ns]
 1   Aluminum Dissolved             3 non-null      float64
 2   Aluminum Total Recoverable     3 non-null      float64
 3   Calcium Dissolved              9 non-null      float64
 4   Copper Dissolved               3 non-null      float64
 5   Copper Total Recoverable       3 non-null      float64
 6   Lead Dissolved                 3 non-null      float64
 7   Lead Total Recoverable         3 non-null      float64
 8   Nickel Dissolved               3 non-null      float64
 9   Nickel Total Recoverable       3 non-null      float64
 10  Nitrogen Dissolved             9 non-null      float64
 11  Phosphorus Total Dissolved     9 non-null      float64
 12  Phosphorus Total               9 non-null      float64
 13  Vanadium Dissolved             3 non-null      float64
 14  Turbidity                      9 non-null      float64
 15  pH                             9 non-null      float64
 16  Oxygen dissolved % saturation  0 non-null      float64
 17  Site Name                      18 non-null     object
 18  Unit Symbol                    18 non-null     object
dtypes: datetime64[ns](1), float64(16), object(2)
memory usage: 2.8+ KB

In [25]:
df.to_csv("Touchwood_Data.csv", index = True)