In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("gregoire_river_cleaned.csv")

In [2]:
df

,lake,parameter,source_file,sampling_timestamp,sample_timestamp,measurement_value,measurement_value_raw,site_name,station_name,depth,value_sign,unit_symbol,method,laboratory,sampling_number,sample_number,rdl,sample_location,sample_type,vanadium_total_recoverable
0,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-07-10 12:00:00,2014-07-10 11:00:00,2.61,2.61,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),107356,NaN,0.00001,NaN,NaN,2.61
1,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-09-07 12:00:00,2014-09-07 11:00:00,7.19,7.19,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),107362,NaN,0.00001,NaN,NaN,7.19
2,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2015-03-02 12:00:00,2015-03-02 12:00:00,0.59,0.59,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),107359,NaN,0.00001,NaN,NaN,0.59
3,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-03-10 12:00:00,2016-03-10 12:00:00,0.58,0.58,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),112660,NaN,0.00001,NaN,NaN,0.58
4,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-07-20 12:00:00,2016-07-20 11:00:00,1.53,1.53,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),112405,NaN,0.00001,NaN,NaN,1.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2015-03-02 12:00:00,2015-03-02 12:00:00,4.79,4.79,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),107359,NaN,0.00013,NaN,NaN,4.79
167,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-03-10 12:00:00,2016-03-10 12:00:00,2.85,2.85,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),112660,NaN,0.00013,NaN,NaN,2.85
168,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-07-20 12:00:00,2016-07-20 11:00:00,40.00,40,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),112405,NaN,0.00013,NaN,NaN,40
169,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-09-21 12:00:00,2016-09-21 11:00:00,25.40,25.4,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),112207,NaN,0.00013,NaN,NaN,25.4
170,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2017-03-15 12:00:00,2017-03-15 11:00:00,8.91,8.91,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),111901,NaN,0.00013,NaN,NaN,8.91

In [3]:
rows_mg = df[df["unit_symbol"] == "mg/l"]

rows_mg

,lake,parameter,source_file,sampling_timestamp,sample_timestamp,measurement_value,measurement_value_raw,site_name,station_name,depth,value_sign,unit_symbol,method,laboratory,sampling_number,sample_number,rdl,sample_location,sample_type,vanadium_total_recoverable
24,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-05-08 12:00:00,2014-05-08 11:00:00,0.1930,0.193,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,567,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",106707,NaN,0.001,NaN,NaN,0.193
25,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-07-10 12:00:00,2014-07-10 11:00:00,0.0654,0.0654,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,567,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",107356,NaN,0.001,NaN,NaN,0.0654
26,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-09-07 12:00:00,2014-09-07 11:00:00,0.0597,0.0597,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,567,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",107362,NaN,0.001,NaN,NaN,0.0597
27,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2015-03-02 12:00:00,2015-03-02 12:00:00,0.0381,0.0381,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,567,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",107359,NaN,0.001,NaN,NaN,0.0381
28,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-03-10 12:00:00,2016-03-10 12:00:00,0.0410,0.041,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,443,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",112660,NaN,0.003,NaN,NaN,0.041
29,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-07-20 12:00:00,2016-07-20 11:00:00,0.0620,0.062,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,443,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",112405,NaN,0.003,NaN,NaN,0.062
30,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-09-21 12:00:00,2016-09-21 11:00:00,0.0720,0.072,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,443,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",112207,NaN,0.003,NaN,NaN,0.072
31,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2017-03-15 12:00:00,2017-03-15 11:00:00,0.0410,0.041,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,443,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",111901,NaN,0.003,NaN,NaN,0.041
34,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-05-08 12:00:00,2014-05-08 11:00:00,0.0248,0.0248,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,567,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",106707,NaN,0.001,NaN,NaN,0.0248
35,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-07-10 12:00:00,2014-07-10 11:00:00,0.0351,0.0351,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,567,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",107356,NaN,0.001,NaN,NaN,0.0351
36,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-09-07 12:00:00,2014-09-07 11:00:00,0.0072,0.0072,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,567,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",107362,NaN,0.001,NaN,NaN,0.0072
37,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2015-03-02 12:00:00,2015-03-02 12:00:00,0.0214,0.0214,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,567,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",107359,NaN,0.001,NaN,NaN,0.0214
38,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-03-10 12:00:00,2016-03-10 12:00:00,0.0240,0.024,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,443,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",112660,NaN,0.003,NaN,NaN,0.024
39,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-07-20 12:00:00,2016-07-20 11:00:00,0.0270,0.027,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,443,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",112405,NaN,0.003,NaN,NaN,0.027
40,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-09-21 12:00:00,2016-09-21 11:00:00,0.0220,0.022,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,443,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",112207,NaN,0.003,NaN,NaN,0.022
41,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2017-03-15 12:00:00,2017-03-15 11:00:00,0.0170,0.017,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,443,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",111901,NaN,0.003,NaN,NaN,0.017
54,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-05-08 12:00:00,2014-05-08 11:00:00,1.0000,2,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,<,mg/l,331,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",106707,NaN,2,NaN,NaN,2
55,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-07-10 12:00:00,2014-07-10 11:00:00,1.0000,2,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,<,mg/l,331,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",107356,NaN,2,NaN,NaN,2
56,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-09-07 12:00:00,2014-09-07 11:00:00,1.0000,2,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,<,mg/l,331,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",107362,NaN,2,NaN,NaN,2
57,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2015-03-02 12:00:00,2015-03-02 12:00:00,1.0000,2,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,<,mg/l,331,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",107359,NaN,2,NaN,NaN,2
58,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-03-10 12:00:00,2016-03-10 12:00:00,1.0000,2,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,<,mg/l,331,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",112660,NaN,2,NaN,NaN,2
61,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-05-08 12:00:00,2014-05-08 11:00:00,1.0000,1,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,301,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",106707,NaN,NaN,NaN,NaN,1
62,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-07-10 12:00:00,2014-07-10 11:00:00,0.6040,0.604,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,301,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",107356,NaN,NaN,NaN,NaN,0.604
63,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-09-07 12:00:00,2014-09-07 11:00:00,0.4740,0.474,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,301,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",107362,NaN,NaN,NaN,NaN,0.474
64,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2015-03-02 12:00:00,2015-03-02 12:00:00,0.6340,0.634,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,301,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",107359,NaN,NaN,NaN,NaN,0.634
65,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-03-10 12:00:00,2016-03-10 12:00:00,1.2000,1.2,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,301,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",112660,NaN,0.055,NaN,NaN,1.2
66,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-07-20 12:00:00,2016-07-20 11:00:00,0.7900,0.79,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,301,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",112405,NaN,0.055,NaN,NaN,0.79
67,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-09-21 12:00:00,2016-09-21 11:00:00,0.7900,0.79,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,301,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",112207,NaN,0.055,NaN,NaN,0.79
68,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2017-03-15 12:00:00,2017-03-15 11:00:00,0.8900,0.89,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,301,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",111901,NaN,0.055,NaN,NaN,0.89
125,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-07-10 12:00:00,2014-07-10 11:00:00,21.9000,21.9,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),107356,NaN,0.01,NaN,NaN,21.9
126,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-09-07 12:00:00,2014-09-07 11:00:00,33.8000,33.8,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),107362,NaN,0.01,NaN,NaN,33.8
127,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2015-03-02 12:00:00,2015-03-02 12:00:00,31.0000,31,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),107359,NaN,0.01,NaN,NaN,31
128,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-03-10 12:00:00,2016-03-10 12:00:00,50.4000,50.4,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),112660,NaN,0.01,NaN,NaN,50.4
129,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-07-20 12:00:00,2016-07-20 11:00:00,28.7000,28.7,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),112405,NaN,0.01,NaN,NaN,28.7
130,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-09-21 12:00:00,2016-09-21 11:00:00,26.1000,26.1,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),112207,NaN,0.01,NaN,NaN,26.1
131,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2017-03-15 12:00:00,2017-03-15 11:00:00,41.7000,41.7,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),111901,NaN,0.01,NaN,NaN,41.7
132,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-03-10 12:00:00,2016-03-10 12:00:00,59.0000,59,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,440,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",112660,NaN,0.3,NaN,NaN,59
133,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-07-20 12:00:00,2016-07-20 11:00:00,30.0000,30,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,440,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",112405,NaN,0.3,NaN,NaN,30
134,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-09-21 12:00:00,2016-09-21 11:00:00,29.0000,29,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,440,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",112207,NaN,0.3,NaN,NaN,29
135,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2017-03-15 12:00:00,2017-03-15 11:00:00,44.0000,44,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,440,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",111901,NaN,0.3,NaN,NaN,44
138,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-05-08 12:00:00,2014-05-08 11:00:00,23.9000,23.9,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,3158,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",106707,NaN,0.5,NaN,NaN,23.9
139,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-07-10 12:00:00,2014-07-10 11:00:00,26.4000,26.4,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,3158,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",107356,NaN,0.5,NaN,NaN,26.4
140,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-09-07 12:00:00,2014-09-07 11:00:00,39.7000,39.7,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,3158,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",107362,NaN,0.5,NaN,NaN,39.7
141,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2015-03-02 12:00:00,2015-03-02 12:00:00,33.0000,33,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,3158,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",107359,NaN,0.5,NaN,NaN,33
142,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-07-10 12:00:00,2014-07-10 11:00:00,21.0000,21,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),107356,NaN,0.03,NaN,NaN,21
143,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-09-07 12:00:00,2014-09-07 11:00:00,33.6000,33.6,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),107362,NaN,0.03,NaN,NaN,33.6
144,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2015-03-02 12:00:00,2015-03-02 12:00:00,29.0000,29,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),107359,NaN,0.03,NaN,NaN,29
145,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-03-10 12:00:00,2016-03-10 12:00:00,50.2000,50.2,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),112660,NaN,0.03,NaN,NaN,50.2
146,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-07-20 12:00:00,2016-07-20 11:00:00,28.6000,28.6,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),112405,NaN,0.03,NaN,NaN,28.6
147,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-09-21 12:00:00,2016-09-21 11:00:00,25.5000,25.5,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),112207,NaN,0.03,NaN,NaN,25.5
148,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2017-03-15 12:00:00,2017-03-15 11:00:00,40.5000,40.5,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),111901,NaN,0.03,NaN,NaN,40.5
149,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-03-10 12:00:00,2016-03-10 12:00:00,64.0000,64,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,1516,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",112660,NaN,0.3,NaN,NaN,64
150,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-07-20 12:00:00,2016-07-20 11:00:00,30.0000,30,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,1516,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",112405,NaN,0.3,NaN,NaN,30
151,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-09-21 12:00:00,2016-09-21 11:00:00,30.0000,30,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,1516,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",112207,NaN,0.3,NaN,NaN,30
152,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2017-03-15 12:00:00,2017-03-15 11:00:00,43.0000,43,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,mg/l,1516,"MAXXAM (CHEMEX) LABS ALBERTA INC., CALGARY, AL...",111901,NaN,0.3,NaN,NaN,43

In [4]:
dfunits = df.copy()

dfunits["vanadium_total_recoverable"] = pd.to_numeric(
    dfunits["vanadium_total_recoverable"], errors="coerce"
)

condition = dfunits['unit_symbol'] == 'mg/l'
dfunits.loc[condition, 'vanadium_total_recoverable'] *= 1000
dfunits.loc[condition, 'unit_symbol'] = 'µg/l'

dfunits

,lake,parameter,source_file,sampling_timestamp,sample_timestamp,measurement_value,measurement_value_raw,site_name,station_name,depth,value_sign,unit_symbol,method,laboratory,sampling_number,sample_number,rdl,sample_location,sample_type,vanadium_total_recoverable
0,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-07-10 12:00:00,2014-07-10 11:00:00,2.61,2.61,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),107356,NaN,0.00001,NaN,NaN,2.61
1,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2014-09-07 12:00:00,2014-09-07 11:00:00,7.19,7.19,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),107362,NaN,0.00001,NaN,NaN,7.19
2,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2015-03-02 12:00:00,2015-03-02 12:00:00,0.59,0.59,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),107359,NaN,0.00001,NaN,NaN,0.59
3,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-03-10 12:00:00,2016-03-10 12:00:00,0.58,0.58,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),112660,NaN,0.00001,NaN,NaN,0.58
4,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-07-20 12:00:00,2016-07-20 11:00:00,1.53,1.53,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),112405,NaN,0.00001,NaN,NaN,1.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2015-03-02 12:00:00,2015-03-02 12:00:00,4.79,4.79,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),107359,NaN,0.00013,NaN,NaN,4.79
167,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-03-10 12:00:00,2016-03-10 12:00:00,2.85,2.85,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),112660,NaN,0.00013,NaN,NaN,2.85
168,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-07-20 12:00:00,2016-07-20 11:00:00,40.00,40,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),112405,NaN,0.00013,NaN,NaN,40.00
169,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2016-09-21 12:00:00,2016-09-21 11:00:00,25.40,25.4,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),112207,NaN,0.00013,NaN,NaN,25.40
170,gregoire_river,vanadium_total_recoverable,GREGOIRE RIVER.csv,2017-03-15 12:00:00,2017-03-15 11:00:00,8.91,8.91,GREGOIRE RIVER,(LOWER) APPROX 2KM UPSTREAM CONFLUENCE WITH CH...,NaN,NaN,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),111901,NaN,0.00013,NaN,NaN,8.91

In [5]:
rows_mg = dfunits[dfunits["unit_symbol"] == "mg/l"]

rows_mg

Empty DataFrame
Columns: [lake, parameter, source_file, sampling_timestamp, sample_timestamp, measurement_value, measurement_value_raw, site_name, station_name, depth, value_sign, unit_symbol, method, laboratory, sampling_number, sample_number, rdl, sample_location, sample_type, vanadium_total_recoverable]
Index: []

In [6]:
df_clean = dfunits.drop(columns=[
    "parameter",
    "source_file",
    "sample_timestamp",
    "measurement_value_raw",
    "station_name",
    "method",
    "sampling_number",
    "sample_number",
    "sample_location",
    "sample_type"

])
df_clean

,lake,sampling_timestamp,measurement_value,site_name,depth,value_sign,unit_symbol,laboratory,rdl,vanadium_total_recoverable
0,gregoire_river,2014-07-10 12:00:00,2.61,GREGOIRE RIVER,NaN,NaN,µg/l,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.00001,2.61
1,gregoire_river,2014-09-07 12:00:00,7.19,GREGOIRE RIVER,NaN,NaN,µg/l,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.00001,7.19
2,gregoire_river,2015-03-02 12:00:00,0.59,GREGOIRE RIVER,NaN,NaN,µg/l,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.00001,0.59
3,gregoire_river,2016-03-10 12:00:00,0.58,GREGOIRE RIVER,NaN,NaN,µg/l,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.00001,0.58
4,gregoire_river,2016-07-20 12:00:00,1.53,GREGOIRE RIVER,NaN,NaN,µg/l,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.00001,1.53
...,...,...,...,...,...,...,...,...,...,...
166,gregoire_river,2015-03-02 12:00:00,4.79,GREGOIRE RIVER,NaN,NaN,µg/l,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.00013,4.79
167,gregoire_river,2016-03-10 12:00:00,2.85,GREGOIRE RIVER,NaN,NaN,µg/l,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.00013,2.85
168,gregoire_river,2016-07-20 12:00:00,40.00,GREGOIRE RIVER,NaN,NaN,µg/l,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.00013,40.00
169,gregoire_river,2016-09-21 12:00:00,25.40,GREGOIRE RIVER,NaN,NaN,µg/l,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.00013,25.40
170,gregoire_river,2017-03-15 12:00:00,8.91,GREGOIRE RIVER,NaN,NaN,µg/l,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.00013,8.91

In [7]:
rows_mg = df_clean[df_clean["unit_symbol"] == "mg/l"]

rows_mg

Empty DataFrame
Columns: [lake, sampling_timestamp, measurement_value, site_name, depth, value_sign, unit_symbol, laboratory, rdl, vanadium_total_recoverable]
Index: []

In [8]:
header_indices = df_clean[df_clean['site_name'] == 'Site Name'].index.tolist()
print(header_indices)
print(len(header_indices))

[8, 17, 23, 33, 43, 53, 60, 70, 79, 88, 97, 106, 115, 124, 137, 154, 163]
17

In [9]:
starts = [8, 17, 23, 33, 43, 53, 60, 70, 79, 88, 97, 106, 115, 124, 137, 154, 163]

dfs = []

for i in range(len(starts)):
    
    start = starts[i]
    
    if i < len(starts) - 1:
        end = starts[i+1]
        df_split = df_clean.iloc[start:end]
    else:
        df_split = df_clean.iloc[start:]   # last section
    
    dfs.append(df_split)

In [13]:
#clean_dfs = []

for d in dfs:
    
    chem_name = d.iloc[0, -1]   # chemical name from header row
    
    d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
    
    d.drop(index=d.index[0], inplace=True)  # remove header row

C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_30888\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row

In [29]:
"""for i, d in enumerate(clean_dfs):
    print(f"\nDataFrame {i}")
    print(d)"""
dfs[14].head()

,lake,sampling_timestamp,measurement_value,site_name,depth,value_sign,unit_symbol,laboratory,rdl,Calcium Dissolved
138,gregoire_river,2014-05-08 12:00:00,23.9,GREGOIRE RIVER,NaN,NaN,µg/l,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",0.5,23900.0
139,gregoire_river,2014-07-10 12:00:00,26.4,GREGOIRE RIVER,NaN,NaN,µg/l,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",0.5,26400.0
140,gregoire_river,2014-09-07 12:00:00,39.7,GREGOIRE RIVER,NaN,NaN,µg/l,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",0.5,39700.0
141,gregoire_river,2015-03-02 12:00:00,33.0,GREGOIRE RIVER,NaN,NaN,µg/l,"ALS (FORMERLY ENVIRO-TEST) LABORATORIES, EDMON...",0.5,33000.0
142,gregoire_river,2014-07-10 12:00:00,21.0,GREGOIRE RIVER,NaN,NaN,µg/l,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),0.03,21000.0

In [28]:
# Aluminum
dfs[16] = dfs[16].rename(columns={dfs[16].columns[-1]: "Aluminum Dissolved"})
aluminum_df = dfs[16][["sampling_timestamp", "Aluminum Dissolved"]]

dfs[15] = dfs[15].rename(columns={dfs[15].columns[-1]: "Aluminum Total Recoverable"})
aluminum_total_df = dfs[15][["sampling_timestamp", "Aluminum Total Recoverable"]]

# Calcium
dfs[14] = dfs[14].rename(columns={dfs[14].columns[-1]: "Calcium Dissolved"})
calcium_df = dfs[14][["sampling_timestamp", "Calcium Dissolved"]]

dfs[13] = dfs[13].rename(columns={dfs[13].columns[-1]: "Calcium Total"})
calcium_total_df = dfs[13][["sampling_timestamp", "Calcium Total"]]

# Copper
dfs[12] = dfs[12].rename(columns={dfs[12].columns[-1]: "Copper Dissolved"})
copper_df = dfs[12][["sampling_timestamp", "Copper Dissolved"]]

dfs[11] = dfs[11].rename(columns={dfs[11].columns[-1]: "Copper Total Recoverable"})
copper_total_df = dfs[11][["sampling_timestamp", "Copper Total Recoverable"]]

# Lead
dfs[10] = dfs[10].rename(columns={dfs[10].columns[-1]: "Lead Dissolved"})
lead_df = dfs[10][["sampling_timestamp", "Lead Dissolved"]]

dfs[9] = dfs[9].rename(columns={dfs[9].columns[-1]: "Lead Total Recoverable"})
lead_total_df = dfs[9][["sampling_timestamp", "Lead Total Recoverable"]]

# Nickel
dfs[8] = dfs[8].rename(columns={dfs[8].columns[-1]: "Nickel Dissolved"})
nickel_df = dfs[8][["sampling_timestamp", "Nickel Dissolved"]]

dfs[7] = dfs[7].rename(columns={dfs[7].columns[-1]: "Nickel Total Recoverable"})
nickel_total_df = dfs[7][["sampling_timestamp", "Nickel Total Recoverable"]]

# Nitrogen
dfs[6] = dfs[6].rename(columns={dfs[6].columns[-1]: "Nitrogen Total"})
nitrogen_df = dfs[6][["sampling_timestamp", "Nitrogen Total"]]

# Phosphorus
dfs[3] = dfs[3].rename(columns={dfs[3].columns[-1]: "Phosphorus Total Dissolved"})
phosphorus_df = dfs[3][["sampling_timestamp", "Phosphorus Total Dissolved"]]

dfs[2] = dfs[2].rename(columns={dfs[2].columns[-1]: "Phosphorus Total"})
phosphorus_total_df = dfs[2][["sampling_timestamp", "Phosphorus Total"]]

# Vanadium
dfs[0] = dfs[0].rename(columns={dfs[0].columns[-1]: "Vanadium Dissolved"})
vanadium_df = dfs[0][["sampling_timestamp", "Vanadium Dissolved"]]

# Turbidity
dfs[1] = dfs[1].rename(columns={dfs[1].columns[-1]: "Turbidity"})
turbidity_df = dfs[1][["sampling_timestamp", "Turbidity"]]

# pH
dfs[4] = dfs[4].rename(columns={dfs[4].columns[-1]: "pH"})
ph_df = dfs[4][["sampling_timestamp", "pH"]]

# Oxygen BOD
dfs[5] = dfs[5].rename(columns={dfs[5].columns[-1]: "OXYGEN BIOCHEMICAL DEMAND"})
oxygen_bod_df = dfs[5][["sampling_timestamp", "OXYGEN BIOCHEMICAL DEMAND"]]

In [30]:
calcium_df

      sampling_timestamp  Calcium Dissolved
138  2014-05-08 12:00:00            23900.0
139  2014-07-10 12:00:00            26400.0
140  2014-09-07 12:00:00            39700.0
141  2015-03-02 12:00:00            33000.0
142  2014-07-10 12:00:00            21000.0
143  2014-09-07 12:00:00            33600.0
144  2015-03-02 12:00:00            29000.0
145  2016-03-10 12:00:00            50200.0
146  2016-07-20 12:00:00            28600.0
147  2016-09-21 12:00:00            25500.0
148  2017-03-15 12:00:00            40500.0
149  2016-03-10 12:00:00            64000.0
150  2016-07-20 12:00:00            30000.0
151  2016-09-21 12:00:00            30000.0
152  2017-03-15 12:00:00            43000.0
153                  NaN                NaN

In [32]:
GREGOIRE = pd.concat(
    [
        aluminum_df,
        aluminum_total_df,
        calcium_df,
        calcium_total_df,
        copper_df,
        copper_total_df,
        lead_df,
        lead_total_df,
        nickel_df,
        nickel_total_df,
        nitrogen_df,
        phosphorus_df,
        phosphorus_total_df,
        vanadium_df,
        turbidity_df,
        ph_df,
        #oxygen_sat_df,
        oxygen_bod_df
    ],
    axis=0
)


GREGOIRE ["Site Name"] = "gregoire LAKE"
GREGOIRE ["Unit Symbol"] = "µg/l"

GREGOIRE = GREGOIRE .groupby("sampling_timestamp", as_index=False).first()

GREGOIRE ["sampling_timestamp"] = pd.to_datetime(
    GREGOIRE ["sampling_timestamp"], errors="coerce"
)

In [33]:
GREGOIRE  = GREGOIRE .sort_values(by="sampling_timestamp")
GREGOIRE

,sampling_timestamp,Aluminum Dissolved,Aluminum Total Recoverable,Calcium Dissolved,Calcium Total,Copper Dissolved,Copper Total Recoverable,Lead Dissolved,Lead Total Recoverable,Nickel Dissolved,Nickel Total Recoverable,Nitrogen Total,Phosphorus Total Dissolved,Phosphorus Total,Vanadium Dissolved,Turbidity,pH,OXYGEN BIOCHEMICAL DEMAND,Site Name,Unit Symbol
0,2014-05-08 12:00:00,NaN,NaN,23900.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,24.8,193.0,NaN,NaN,7.75,2000.0,gregoire LAKE,µg/l
1,2014-07-10 12:00:00,20.10,1540.0,26400.0,21900.0,0.82,1.17,0.061,0.475,0.920,1.480,604.0,35.1,65.4,0.39,NaN,7.84,2000.0,gregoire LAKE,µg/l
2,2014-09-07 12:00:00,19.40,3500.0,39700.0,33800.0,0.73,2.05,0.040,1.170,0.755,2.650,474.0,7.2,59.7,0.25,NaN,8.22,2000.0,gregoire LAKE,µg/l
3,2015-03-02 12:00:00,4.79,259.0,33000.0,31000.0,0.45,0.68,0.011,0.094,0.648,0.805,634.0,21.4,38.1,0.14,NaN,7.74,2000.0,gregoire LAKE,µg/l
4,2016-03-10 12:00:00,2.85,239.0,50200.0,50400.0,0.55,0.56,0.046,0.100,0.598,0.605,1200.0,24.0,41.0,0.18,4.5,7.79,2000.0,gregoire LAKE,µg/l
5,2016-07-20 12:00:00,40.00,519.0,28600.0,28700.0,0.94,1.26,0.092,0.332,1.390,1.860,790.0,27.0,62.0,0.58,13.0,8.11,NaN,gregoire LAKE,µg/l
6,2016-09-21 12:00:00,25.40,534.0,25500.0,26100.0,1.20,1.22,0.102,0.538,1.200,1.920,790.0,22.0,72.0,0.36,15.0,8.12,NaN,gregoire LAKE,µg/l
7,2017-03-15 12:00:00,8.91,96.2,40500.0,41700.0,0.61,0.85,0.025,0.149,1.320,1.810,890.0,17.0,41.0,0.15,7.8,7.84,NaN,gregoire LAKE,µg/l

In [ ]:
GREGOIRE.info()

In [34]:
GREGOIRE.to_csv("gregoireLake_Data.csv", index= False)